#Lan Xang

#-----------------------------------------------------------------------------------------------

country = {
	tag = AMI
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = {
		type = thai
	}
	diplomacy = {
		relation = { tag = ANN value = 125 }
		relation = { tag = DAI value = 100 }
		relation = { tag = AYU value = 65 }
		relation = { tag = CHA value = 75 }
		relation = { tag = CAM value = 100 }
	}
	knownprovinces = {
		555 556 557 558 559 641 642 649 650 652 653 654 655 656 657 658 659 660 661 662 663 
		664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 683 684 685 686 
		687 688 940 941 942 944 1018 1019 1020 1021 1078 1079 1080 1081 1082 1083 1084 1085 
		1143 1144 1145 1146 1147 1149 1351 1356 1357 1358 1544 1545 1546 1547 1548 1549 1550 
		1551 1552 1553 1554 1555 1556 1557 
	}
	ownedprovinces = {
		1552 1551 669 1549 1550
	}
	controlledprovinces = {
		1552 1551 669 1549 1550
	}
	nationalprovinces = {
		1552 1551 669
	}
	city = {
		fortress = { level = 2 }
		population = 19500
		location = 1552
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 2 }
		population = 15000
		location = 1551
		capital = yes
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 13000
		location = 669
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 14000
		location = 1550
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 14000
		location = 1549
		bailiff = yes
		courthouse = yes
	}
	landunit = {
		id = { type = 9423 id = 1128 }
		location = 1551
		infantry = 10000
		cavalry = 3000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 600 }
		trade = { level = 4 value = 100 }
		land = { level = 18 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
