#Mali

#-----------------------------------------------------------------------------------------------

country = {
	tag = MAL
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = mali }
	diplomacy = {
		relation = { tag = MOR value = 25 }
	}
	knownprovinces = {
		744 791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1595
	}
	ownedprovinces = {
		1487 1488 1489 1491 1492
	}
	controlledprovinces = {
		1487 1488 1489 1491 1492
	}
	nationalprovinces = {
		1489 1491 1492
	}
	city = {
		fortress = { level = 1 }
		population = 13000
		location = 1492
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1491
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 9000
		location = 1489
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 1488
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1487
		bailiff = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 2000 }
		trade = { level = 3 value = 300 }
		land = { level = 11 value = 400 }
		naval = { level = 6 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
