#Ethiopia

#-----------------------------------------------------------------------------------------------

country = {
	tag = ETH
	ai = "Large.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = miaphysite }
	culture = { type = ethiopian }
	diplomacy = { }
	knownprovinces = {
		752 753 1516 1517 1588 1589 1590 754 755 757 758 1519 760 761 743 744 745 746 747 748 749 750 751
		1059 1060 1061 1062 498 497 499 500 1518 759
	}
	ownedprovinces = {
		753 758 1516 1517 1518 1519 1588 1589 1590
	}
	controlledprovinces = {
		753 758 1516 1517 1518 1519 1588 1589 1590
	}
	nationalprovinces = {
		752 753 758 1516 1517 1518 1519 1588 1589 1590
	}
	city = {
		fortress = { level = 1 }
		population = 6500
		bailiff = yes
		courthouse = yes
		location = 753
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		bailiff = yes
		courthouse = yes
		location = 1517
	}
	city = {
		fortress = { level = 2 }
		population = 10000
		location = 1516
		bailiff = yes
		courthouse = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1588
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 1589
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 1590
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 1519
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 1518
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 758
		bailiff = yes
		courthouse = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 600 }
		trade = { level = 3 value = 1300 }
		land = { level = 15 value = 500 }
		naval = { level = 5 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
