#Khanate of Khiva

#-----------------------------------------------------------------------------------------------

country = {
	tag = KHI
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = canary }
	diplomacy = {
		relation = { tag = UZB value = 50 }
		relation = { tag = PER value = -200 }
	}
	knownprovinces = {
		272 296 357 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466
		467 468 477 498 504 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
		526 527 528 529 530 531 532 533 534 535 579 1527 1528 1529 1530 1531 1532 1533 1534
		1535 1536 1573 1591 1592 1593 1594 1598 1599 1600 1601
		#Siberian corridor - South
		1572 580 582 584 585 587 589
	}
	ownedprovinces = {
		1533 1534 521 522 523 524
	}
	controlledprovinces = {
		1533 1534 521 522 523 524
	}
	nationalprovinces = {
		521 522 523 524 1533
	}
	city = {
		fortress = { level = 2 }
		population = 17500
		location = 1533
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 16500
		location = 1534
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 521
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 17000
		location = 522
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 524
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 523
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 1056 }
		name = "Khiva Army"
		location = 1533
		infantry = 5000
		cavalry = 10000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 100 }
		trade = { level = 3 value = 350 }
		land = { level = 18 value = 100 }
		naval = { level = 0 value = 0 }
		group = china
	}
}

#-----------------------------------------------------------------------------------------------
