#Benin

#-----------------------------------------------------------------------------------------------

country = {
	tag = BEN
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = yoruba }
	diplomacy = {
		relation = { tag = DAH value = 25 }
		relation = { tag = HAS value = 75 }
	}
	knownprovinces = {
		441 791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 
		1499 1500 1501 1502 
	}
	ownedprovinces = {
		791 792 793
	}
	controlledprovinces = {
		791 792 793
	}
	nationalprovinces = {
		792
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 792
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 793
		bailiff =yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 791
		bailiff = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 900 }
		trade = { level = 2 value = 1750 }
		land = { level = 12 value = 50 }
		naval = { level = 10 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
