#Golconda

#-----------------------------------------------------------------------------------------------

country = {
	tag = HYD
	ai = "HYD_1419_Golconda.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = sunni }
	culture = { type = cambodian }
	diplomacy = {
		relation = { tag = MYS value = -50 }
		relation = { tag = FAT value = 140 }
		relation = { tag = MOG value = 110 }}

	knownprovinces = {
		441 501 504 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 
		551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 
		572 573 574 575 576 577 671 672 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 
		1072 1073 1074 1078 1135 1138 1140 1363 1520 1521 1522 1523 1524 1525 1526 1527 1528 
		1531 1539 1540 1541 1542 1543 1545 1546 1591 1592 
		#Extension for Malacca
		1075 1076 1077 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		566 567
	}
	controlledprovinces = {
		566 567
	}
	nationalprovinces = {
		563 565 566
	}
	city = {
		name = "Golconda"
		fortress = { level = 2 }
		population = 33500
		location = 566
		bailiff = yes
		courthouse = yes
		capital = yes
	}
	city = {
		name = "Bangalore"
		fortress = { level = 1 }
		population = 18500
		location = 567
		bailiff = yes
		courthouse = yes
	}
	landunit = {
		id = { type = 9423 id = 1062 }
		name = "Golconda Amry"
		location = 566
		infantry = 12000
		cavalry = 6000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 600 }
		trade = { level = 4 value = 800 }
		land = { level = 21 value = 200 }
		naval = { level = 16 value = 100 }
	}
}

#-----------------------------------------------------------------------------------------------
