#Madurai

#-----------------------------------------------------------------------------------------------

country = {
	tag = MAD
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = hindu }
	culture = { type = tamil }
	diplomacy = { }
	knownprovinces = {
		570 571 572 573 574 575 576 577 560 561 562 563 564 565 566 567 568 569 540 541 542
		543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 539 1523 1539
		1520 1521 1522 504 501 1068 1069 1070 1071 1138 1140 1061 1062 1135 1064 1065 1066 1067
		#Extension for Malacca
		1075 1076 1077 1078 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		575
	}
	controlledprovinces = {
		575
	}
	nationalprovinces = {
		575
	}
	city = {
		fortress = { level = 1 }
		population = 26000
		location = 575
		bailiff = yes
		capital = yes
		courthouse = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 100 }
		trade = { level = 4 value = 100 }
		land = { level = 18 value = 900 }
		naval = { level = 16 value = 600 }
	}
}

#-----------------------------------------------------------------------------------------------
