#Songhai

#-----------------------------------------------------------------------------------------------

country = {
	tag = SON
	ai = "SON_1600_Mohammad.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = mali }
	diplomacy = {
		relation = { tag = MOR value = -200 }
	}
	knownprovinces = {
		791 792 793 794 795 805 806 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 
		1499 1500 1501 1502 1595 1596 1597 
	}
	ownedprovinces = {
		1497
	}
	controlledprovinces = {
		1497
	}
	nationalprovinces = {
		1496 1497
	}
	city = {
		fortress = { level = 2 }
		population = 13500
		location = 1497
		capital = yes
		bailiff = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 1500 }
		trade = { level = 3 value = 1700 }
		land = { level = 15 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
