#Kongo

#-----------------------------------------------------------------------------------------------

country = {
	tag = KON
	ai = "Large.txt"
	monarchtable = "scenarios\1648\monarchs\monarchs_kon.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = catholic }
	culture = { type = kongolese }
	diplomacy = { }
	knownprovinces = {
		399 441 762 766 783 784 785 786 787 788 789 793 1503 1504 1505 1506
	}
	ownedprovinces = {
		785 786 787 1505 1506
	}
	controlledprovinces = {
		785 786 787 1505 1506
	}
	nationalprovinces = {
		785 786 787 1505 1506
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1506
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1505
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 786
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 787
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 785
		capital = yes
		bailiff = yes
	}
	technology = {
		stability = { level = 3 value = 42 }
		infra = { level = 2 value = 1000 }
		trade = { level = 2 value = 1000 }
		land = { level = 8 value = 700 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
