#Mysore

#-----------------------------------------------------------------------------------------------

country = {
	tag = MYS
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = hinduism }
	culture = { type = dravidian }
	diplomacy = {
		relation = { tag = HYD value = -50 }
		relation = { tag = FAT value = 130 }
		relation = { tag = TAN value = 130 }
	}
	knownprovinces = {
		570 571 572 573 574 575 576 577 560 561 562 563 564 565 566 567 568 569 540 541 542
		543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 539 1523 1539
		1520 1521 1522 504 501 1068 1069 1070 1071 1138 1140 1061 1062 1135 1064 1065 1066 1067
		#Extension for Malacca
		1075 1076 1077 1078 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		570 572
	}
	controlledprovinces = {
		570 572
	}
	nationalprovinces = {
		570
	}
	city = {
		fortress = { level = 2 }
		population = 38000
		location = 570
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 572
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 1063 }
		name = "Raja's Guard"
		location = 570
		infantry = 12000
		cavalry = 6000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 1600 }
		trade = { level = 3 value = 1400 }
		land = { level = 20 value = 750 }
		naval = { level = 15 value = 500 }
	}
}

#-----------------------------------------------------------------------------------------------
