#Mogadishu

#-----------------------------------------------------------------------------------------------

country = {
	tag = DEL
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = {
		type = swahili
		type = somali
	}
	diplomacy = {
		relation = { tag = ARM value = 170 refusetrade = no }
		relation = { tag = KIE value = 170 refusetrade = no }
		relation = { tag = ZUL value = 170 refusetrade = no }
	}
	knownprovinces = {
		441 489 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 532 533 534 536 
		537 538 539 541 547 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 
		770 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1133 1134 1135 
		1136 1138 1184 1185 1186 1359 1363 1512 1513 1514 1515 1517 1518 1519 1589 1590 1592 
	}
	ownedprovinces = {
		760 759 757
	}
	controlledprovinces = {
		760 759 757
	}
	nationalprovinces = {
		757 759 760
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		capital = yes
		bailiff = yes
		courthouse = yes
		location = 760
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		bailiff = yes
		location = 759
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		bailiff = yes
		location = 757
		courthouse = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 500 }
		trade = { level = 4 value = 700 }
		land = { level = 15 value = 50 }
		naval = { level = 14 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
