#Arakan

#-----------------------------------------------------------------------------------------------

country = {
	tag = ARK
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = buddhist }
	culture = {
		type = burmese
	}
	diplomacy = {
		relation = { tag = MOG value = -120 }
		relation = { tag = BRM value = 100 }
		relation = { tag = MUB value = 65 }
		relation = { tag = CHA value = 75 }
		relation = { tag = LAX value = 100 }
	}
	knownprovinces = {
		441 543 544 545 553 554 555 556 557 558 559 560 561 565 571 572 653 654 655 656 657 
		658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 
		679 680 1018 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085 1141 
		1142 1143 1144 1145 1146 1147 1149 1351 1356 1357 1358 1543 1544 1545 1546 1547 1548 
		1549 1550 1551 1552 1553 1554 1555 1556 1557 1606 
	}
	ownedprovinces = {
		672 671 556
	}
	controlledprovinces = {
		672 671 556
	}
	nationalprovinces = {
		672 556
	}
	city = {
		fortress = { level = 2 }
		population = 18000
		location = 672
		bailiff = yes
		courthouse = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 671
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 2 }
		population = 33000
		location = 556
		bailiff = yes
		courthouse = yes
	}
	landunit = {
		id = { type = 9423 id = 1132 }
		location = 672
		infantry = 11000
		cavalry = 3000
		artillery = 0
	}
	navalunit = {
		id = { type = 9423 id = 1133 }
		location = 672
		warships = 10
		galleys = 0
		transports = 5
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 1600 }
		trade = { level = 4 value = 800 }
		land = { level = 19 value = 500 }
		naval = { level = 15 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
