#Sennar/Nubia

#-----------------------------------------------------------------------------------------------

country = {
	tag = SUD
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = nubian }
	diplomacy = { }
	knownprovinces = {
		357 497 498 499 500 743 744 745 746 747 748 749 750 751 752 753 754 755 757 758 759 
		760 761 1059 1060 1061 1516 1517 1518 1519 1588 1589 1590 
	}
	ownedprovinces = {
		748 750 751
	}
	controlledprovinces = {
		748 750 751
	}
	nationalprovinces = {
		750 751
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 748
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 9000
		location = 751
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 750
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 1097 }
		location = 751
		infantry = 0
		cavalry = 10000
		artillery = 0
	}
	technology = {
		stability = { level = 1 value = 100 }
		infra = { level = 3 value = 700 }
		trade = { level = 3 value = 200 }
		land = { level = 15 value = 700 }
		naval = { level = 6 value = 800 }
	}
}

#-----------------------------------------------------------------------------------------------
