#Kazakhs

#-----------------------------------------------------------------------------------------------

country = {
	tag = KZK
	ai = "SmallTrade0.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = khazak }
	diplomacy = {
		relation = { tag = KHI value = 50 }
		relation = { tag = PER value = -200 }
	}
	knownprovinces = {
		272 296 357 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466 467 468 477 498
		510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534
		535 579 1527 1528 1529 1530 1531 1532 1533 1534 1535 1536 1573 1591 1592 1593 1594 1598 1599 1600 1601
		#Siberian corridor - South
		1572 580 582 584 585 587 589
	}
	ownedprovinces = {
		1536 1535 516 518 519 520
	}
	controlledprovinces = {
		1536 1535 516 518 519 520
	}
	nationalprovinces = {
		516 517 518 519 520 579 1534 1535 1536
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1536
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1535
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7500
		bailiff = yes
		location = 516
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 518
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 519
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5500
		location = 520
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 1058 }
		name = "Kazakh Raiders"
		location = 1535
		infantry = 0
		cavalry = 15000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 100 }
		trade = { level = 3 value = 350 }
		land = { level = 18 value = 100 }
		naval = { level = 0 value = 0 }
		group = china
	}
}

#-----------------------------------------------------------------------------------------------
