#Hausa

#-----------------------------------------------------------------------------------------------

country = {
	tag = HAS
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = yorumba }
	diplomacy = {
		relation = { tag = SON value = 25 }
		relation = { tag = BEN value = 75 }
	}
	knownprovinces = {
		744 791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1595
	}
	ownedprovinces = {
		1501 1502 1499
	}
	controlledprovinces = {
		1501 1502 1499
	}
	nationalprovinces = {
		1499 1501
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 1501
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 13000
		location = 1502
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 16000
		location = 1499
		bailiff = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 800 }
		trade = { level = 3 value = 1500 }
		land = { level = 13 value = 400 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
