#Japan (Nippon)

#-----------------------------------------------------------------------------------------------

country = {
	tag = NIP
	ai = "NIP_1603_EdoPeriod.ai"
	policy = {
		aristocracy = 5
		centralization = 6
		innovative = 0
		mercantilism = 10
		offensive = 5
		land = 10
		quality = 10
		serfdom = 10
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 300
	inflation = 0
	merchants = 0.983333
	religion = { type = confucianism }
	culture = { type = japanese }
	diplomacy = {
		relation = { tag = HOL value = 150 }
		relation = { tag = SPA value = -200 }
		relation = { tag = CHI value = 50 }
	}
	knownprovinces = {
		625 626 638 639 640 641 642 643 645 646 647 648 649 650 651 652 653 654 655 656 657 658 
		659 660 661 683 684 685 686 687 688 689 886 940 941 942 943 944 945 946 947 948 949 1018
		1019 1020 1021 1082 1085 1087 1088 1089 1352 1086 690
		#Avoid isolation penalty
		596 664 668 670 672 673 678 679 682 1543 1545 1547 1548 1550 1552 1557 1601 1606
	}
	ownedprovinces = {
		683 684 685 686 687 688
	}
	controlledprovinces = {
		683 684 685 686 687 688
	}
	nationalprovinces = {
		683 684 685 686 687 688
	}
	city = {
		fortress = { level = 3 }
		population = 100000
		location = 685
		capital = yes
		courthouse = yes
		manufactory = luxury
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 683
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 40000
		location = 684
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 3 }
		population = 75000
		location = 686
		bailiff = yes
		courthouse = yes
		manufactory = luxury
	}
	city = {
		fortress = { level = 2 }
		population = 30000
		location = 687
		bailiff = yes
		courthouse = yes
		manufactory = weapons
	}
	city = {
		fortress = { level = 3 }
		population = 65000
		location = 688
		bailiff = yes
		courthouse = yes
	}
	landunit = {
		id = { type = 9423 id = 1011 }
		name = "Imperial Army"
		location = 685
		infantry = 30000
		cavalry = 10000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 0 }
		trade = { level = 4 value = 0 }
		land = { level = 22 value = 100 }
		naval = { level = 21 value = 100 }
	}
}

#-----------------------------------------------------------------------------------------------
