#Dahomey

#-----------------------------------------------------------------------------------------------

country = {
	tag = DAH
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = aka }
	diplomacy = { }
	knownprovinces = {
		744 791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1595
	}
	ownedprovinces = {
		1498
	}
	controlledprovinces = {
		1498
	}
	nationalprovinces = {
		793 794 1498
	}
	city = {
		fortress = { level = 1 }
		population = 9000
		location = 1498
		bailiff = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 1600 }
		trade = { level = 2 value = 2500 }
		land = { level = 12 value = 400 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
