#Adal

#-----------------------------------------------------------------------------------------------

country = {
	tag = ADA
	policy = {
		aristocracy = 7
		centralization = 0
		innovative = 4
		mercantilism = 8
		offensive = 8
		land = 6
		quality = 6
		serfdom = 10
	}
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = {
		type = somali
		type = ethiopian
	}
	diplomacy = { }
	knownprovinces = {
		357 495 496 497 498 499 500 501 502 503 504 505 547 743 744 745 746 747 748 749 750 
		751 752 753 754 755 756 757 758 759 760 761 1059 1060 1061 1062 1063 1064 1065 1066 
		1067 1068 1069 1070 1071 1135 1516 1517 1518 1519 1588 1589 1590 
	}
	ownedprovinces = {
		755
	}
	controlledprovinces = {
		755
	}
	nationalprovinces = {
		754 755 1517 1518 1519 758
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 755
		capital = yes
		bailiff = yes
		courthouse = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 700 }
		trade = { level = 4 value = 600 }
		land = { level = 15 value = 500 }
		naval = { level = 12 value = 200 }
	}
}

#-----------------------------------------------------------------------------------------------
