#Bukhara

#-----------------------------------------------------------------------------------------------

country = {
	tag = BUK
	ai = "BUK_1561.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = uzbek }
	diplomacy = {
		relation = { tag = KHI value = 50 }
		relation = { tag = PER value = -200 }
	}
	knownprovinces = {
		272 296 357 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466
		467 468 477 498 504 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
		526 527 528 529 530 531 532 533 534 535 578 579 1527 1528 1529 1530 1531 1532 1533 1534
		1535 1536 1570 1571 1573 1591 1592 1593 1594 1598 1599 1600 1601
		#Siberian corridor - South
		1572 580 582 584 585 587 589
	}
	ownedprovinces = {
		1532 1594 1592 1598 1599 1591
	}
	controlledprovinces = {
		1532 1594 1592 1598 1599 1591
	}
	nationalprovinces = {
		1530 1531 1532 1534 1591 1592 1594 1599
	}
	city = {
		fortress = { level = 1 }
		population = 22000
		location = 1532
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 2 }
		population = 21000
		location = 1592
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 1594
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 13000
		location = 1598
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1599
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 1591
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 1057 }
		name = "Uzbek Raiders"
		location = 1532
		infantry = 5000
		cavalry = 10000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 100 }
		trade = { level = 3 value = 350 }
		land = { level = 18 value = 100 }
		naval = { level = 0 value = 0 }
		group = china
	}
}

#-----------------------------------------------------------------------------------------------
