#Zanzibar

#-----------------------------------------------------------------------------------------------

country = {
	tag = ZAN
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = swahili }
	diplomacy = {
		relation = { tag = MLI value = 155 refusetrade = no }
		relation = { tag = MGU value = 125 refusetrade = no }
		relation = { tag = KIL value = 125 refusetrade = no }
		relation = { tag = ANG value = 125 refusetrade = no }
	}
	knownprovinces = {
		489 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 532 533 534 536 537
		538 539 541 547 569 756 757 759 760 761 762 763 764 765 766 767 768 769 770 771 1059 1060
		1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1133 1134 1135 1136 1138 1184 1185
		1186 1359 1363 1512 1513 1514 1515 1592
	}
	ownedprovinces = {
		765
	}
	controlledprovinces = {
		765
	}
	nationalprovinces = {
		765
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 765
		bailiff = yes
		courthouse = yes
		capital = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 500 }
		trade = { level = 4 value = 850 }
		land = { level = 16 value = 650 }
		naval = { level = 13 value = 650 }
	}
}

#-----------------------------------------------------------------------------------------------
