#Mu Bang

#-----------------------------------------------------------------------------------------------

country = {
	tag = TAU
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = {
		type = burmese
	}
	diplomacy = {
		relation = { tag = ARK value = 75 }
		relation = { tag = DAI value = 100 }
		relation = { tag = AYU value = 25 }
		relation = { tag = MYA value = -25 }
		relation = { tag = CAM value = 100 }
	}
	knownprovinces = {
		543 544 545 553 554 555 556 557 558 559 560 561 565 571 572 641 642 649 650 652 653 
		654 655 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673 674 
		675 676 677 678 679 680 685 686 687 940 941 942 944 1018 1019 1020 1021 1072 1073 1074 
		1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085 1141 1142 1143 1144 1145 1146 
		1147 1149 1351 1356 1357 1358 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 
		1554 1555 1556 1557 1606 
	}
	ownedprovinces = {
		1545 1546
	}
	controlledprovinces = {
		1545 1546
	}
	nationalprovinces = {
		1545 1546
	}
	city = {
		fortress = { level = 2 }
		population = 17000
		location = 1546
		bailiff = yes
		courthouse = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 1545
		bailiff = yes
		courthouse = yes
	}
	landunit = {
		id = { type = 9423 id = 1131 }
		location = 1546
		infantry = 8000
		cavalry = 2000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 600 }
		trade = { level = 4 value = 100 }
		land = { level = 18 value = 50 }
		naval = { level = 12 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
