#The Ottoman Empire

#-----------------------------------------------------------------------------------------------

country = {
	tag = TUR
	ai = "TUR_1640_IbrahimI.ai"
	policy = {
		aristocracy = 10
		centralization = 6
		innovative = 0
		mercantilism = 7
		offensive = 7
		land = 4
		quality = 6
		serfdom = 8
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 1
	cancelledloans = 0
	extendedloans = 0
	treasury = 500
	inflation = 0.1
	merchants = 0
	religion = { type = sunni }
	culture = {
		type = turkish
		type = arabic
		type = slavonic
		type = greek
		type = albanian
		type = delaware
		type = syrian
	}
	diplomacy = {
		relation = { tag = FRA value = 25 }
		relation = { tag = SPA value = -200 }
		relation = { tag = PER value = -200 }
		relation = { tag = CRI value = 125 }
		relation = { tag = MOL value = 150 }
		relation = { tag = WAL value = 150 }
		relation = { tag = POL value = 25 }
		relation = { tag = HAB value = -200 }
		relation = { tag = FRA value = -125 }
		relation = { tag = YEM value = 50 }
		relation = { tag = ETH value = -75 }
	}
	knownprovinces = {
		231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
		252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
		273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293
		294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314
		315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335
		336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356
		357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
		378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398
		399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419
		420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440
		441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461
		462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482
		483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
		504 505 506 507 508 509 510 515 519 520 521 522 523 524 525 526 527 528 529 530 531
		532 533 534 535 536 537 538 539 540 541 542 543 547 548 549 556 568 569 573 574 679
		732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752
		753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 805 806 817
		819 820 821 840 841 842 871 872 873 874 875 876 877 878 879 880 881 882 919 920 921
		922 923 924 925 926 927 928 929 930 931 932 933 934 935 936 937 938 939 979 980 981
		982 983 984 985 986 987 988 989 990 991 992 993 994 995 996 997 998 999 1000 1001 1002
		1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1057 1058
		1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1078
		1079 1080 1133 1134 1135 1136 1138 1140 1143 1184 1185 1186 1326 1327 1331 1359 1361
		1362 1363 1390 1391 1394 1397 1401 1411 1413 1414 1415 1416 1417 1418 1419 1420 1422
		1423 1424 1425 1426 1428 1429 1430 1431 1432 1433 1435 1437 1453 1454 1455 1458 1459
		1460 1461 1462 1469 1470 1490 1493 1494 1495 1496 1497 1498 1516 1517 1518 1519 1523
		1524 1525 1526 1527 1528 1529 1530 1531 1532 1533 1588 1591 1592 1594 1595 1596 1597
		1598 1599 1609 1610 1611 1612 1613 1614
	}
	ownedprovinces = {
		324 325 354 353 355 362 363 364 366 356 358 359 360 465 479 361 481 484 296 319 320 321 357
		473 474 475 476 477 478 1609 1610 1611 482 483 485 486 488 489 508 490 491 492 493 494 495
		496 497 498 752 743 744 745 746 747 749 735 736 737 738 739 740 741 742 464 472 754
	}
	controlledprovinces = {
		324 325 354 353 355 362 363 364 366 356 358 359 360 465 479 361 481 484 296 319 320 321 357
		473 474 475 476 477 478 1609 1610 1611 482 483 485 486 488 489 508 490 491 492 493 494 495
		496 497 498 752 743 744 745 746 747 749 735 736 737 738 739 740 741 742 464 472 754
	}
	nationalprovinces = {
		296 316 317 319 320 321 323 324 325 326 354 351 352 353 355 356 357 358 359 360 361 362 363
		364 365 366 367 464 465 470 472 473 474 475 476 477 478 479 481 482 483 484 485 486 488 489
		490 491 492 493 494 495 496 497 498 508 734 735 736 737 738 739 740 741 742 743 744 745 746
		747 748 749 820 1609 1610 1611
	}
	city = {
		fortress = { level = 3 }
		population = 300000
		location = 357
		capital = yes
		bailiff = yes
		courthouse = yes
		cityrights = yes
		shipyard = yes
		barrack = yes
		manufactory = luxury
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 324
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 32000
		location = 325
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 24000
		location = 353
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 14500
		location = 355
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 20000
		location = 356
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 10000
		location = 354
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 13500
		location = 366
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 9500
		location = 364
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 18500
		location = 362
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 361
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 35000
		location = 358
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 19000
		location = 359
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 360
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6500
		location = 465
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 11500
		location = 479
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 17000
		location = 481
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 25000
		location = 484
		bailiff = yes
		courthouse = yes
		cityrights = yes
		manufactory = refinery
	}
	city = {
		fortress = { level = 2 }
		population = 25500
		location = 477
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 40000
		location = 478
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 17000
		location = 1610
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1611
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 18000
		location = 482
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 14000
		location = 483
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 17000
		location = 476
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 21000
		location = 1609
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 19000
		location = 475
		bailiff = yes
		courthouse = yes
		cityrights = yes
		manufactory = navalequipment
	}
	city = {
		fortress = { level = 1 }
		population = 10500
		location = 474
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 473
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 9000
		location = 486
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 488
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 3 }
		population = 33000
		location = 489
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 25000
		location = 508
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 31000
		location = 485
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 27000
		location = 490
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 22500
		location = 491
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 492
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 493
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 494
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 495
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 496
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 497
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 10000
		location = 498
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 752
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 9500
		location = 749
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 12000
		location = 745
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 55000
		location = 746
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 40000
		location = 744
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 743
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 747
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1200
		location = 742
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 741
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7500
		location = 740
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 3 }
		population = 28000
		location = 739
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 738
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 15000
		location = 737
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 735
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 736
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		name = "Kaffa"
		fortress = { level = 1 }
		population = 6000
		location = 464
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 319
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 320
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 14000
		location = 321
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 9000
		location = 296
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		name = "Niš"
		fortress = { level = 1 }
		population = 12000
		location = 363
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 2 }
		population = 21000
		location = 472
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	city = {
		fortress = { level = 1 }
		population = 17500
		location = 754
		bailiff = yes
		courthouse = yes
		cityrights = yes
	}
	landunit = {
		id = { type = 9423 id = 1103 }
		name = "Janissaries"
		location = 357
		infantry = 30000
		cavalry = 10000
		artillery = 60
	}
	landunit = {
		id = { type = 9423 id = 1104 }
		location = 353
		infantry = 12000
		cavalry = 10000
		artillery = 20
	}
	landunit = {
		id = { type = 9423 id = 1105 }
		location = 489
		infantry = 18000
		cavalry = 12000
		artillery = 30
	}
	landunit = {
		id = { type = 9423 id = 1106 }
		location = 746
		infantry = 10000
		cavalry = 5000
		artillery = 15
	}
	landunit = {
		id = { type = 9423 id = 1111 }
		location = 480
		infantry = 16000
		cavalry = 0
		artillery = 40
	}
	landunit = {
		id = { type = 9423 id = 1107 }
		location = 739
		infantry = 10000
		cavalry = 5000
		artillery = 15
	}
	navalunit = {
		id = { type = 9423 id = 1108 }
		name = "Barbary Corsairs"
		location = 737
		warships = 18
		galleys = 10
		transports = 5
	}
	navalunit = {
		id = { type = 9423 id = 1109 }
		location = 357
		warships = 30
		galleys = 15
		transports = 10
	}
	navalunit = {
		id = { type = 9423 id = 1110 }
		location = 481
		warships = 10
		galleys = 5
		transports = 3
	}
	technology = {
		stability = { level = 1 value = 50 }
		infra = { level = 5 value = 200 }
		trade = { level = 4 value = 2100 }
		land = { level = 25 value = 700 }
		naval = { level = 24 value = 800 }
		group = muslim
	}
}

#-----------------------------------------------------------------------------------------------
