#An Nam

#-----------------------------------------------------------------------------------------------

country = {
	tag = ANN
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = confucianism }
	culture = {
		type = vietnamese
	}
	diplomacy = {
		relation = { tag = DAI value = -200 }
		relation = { tag = CAM value = 100 }
		relation = { tag = AYU value = 65 }
		relation = { tag = CHA value = 75 }
		relation = { tag = AMI value = 100 }
	}
	knownprovinces = {
		556 557 558 641 642 649 650 652 653 654 655 656 657 658 659 660
		661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676
		677 678 679 680 685 686 687 940 941 942 944 1018 1019 1020
		1021 1078 1079 1080 1081 1082 1083 1084 1085 1143 1144 1145
		1146 1147 1149 1351 1356 1357 1358 1544 1545 1546 1547 1548
		1549 1550 1551 1552 1553 1554 1555 1556
	}
	ownedprovinces = {
		664 665
	}
	controlledprovinces = {
		664 665
	}
	nationalprovinces = {
		663 664 665
	}
	city = {
		fortress = { level = 2 }
		population = 17000
		location = 664
		bailiff = yes
		courthouse = yes
		capital = yes
	}
	city = {
		fortress = { level = 2 }
		population = 14000
		location = 665
		bailiff = yes
		courthouse = yes
	}
	landunit = {
		id = { type = 9423 id = 1129 }
		location = 664
		infantry = 17000
		cavalry = 3000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 1600 }
		trade = { level = 4 value = 800 }
		land = { level = 19 value = 500 }
		naval = { level = 11 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
