#Travancore

#-----------------------------------------------------------------------------------------------

country = {
	tag = TAN
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = hinduism }
	culture = { type = lithuanian }
	diplomacy = {
		relation = { tag = MYS value = 100 }
	}
	knownprovinces = {
		501 504 505 506 507 508 509 533 534 535 536 537 538 539 540 541 542 543 544 545 546 
		547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 
		568 569 570 571 572 573 574 575 576 577 671 672 1061 1062 1063 1064 1065 1066 1067 1068 
		1069 1070 1071 1135 1136 1138 1140 1363 1520 1521 1522 1523 1531 1539 
		#Extension for Malacca
		1075 1076 1077 1078 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		574
	}
	controlledprovinces = {
		574
	}
	nationalprovinces = {
		574
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 574
		bailiff = yes
		capital = yes
		courthouse = yes
	}
	landunit = {
		id = { type = 9423 id = 1043 }
		name = "Army of the Venad"
		location = 574
		infantry = 8000
		cavalry = 4000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 100 }
		trade = { level = 4 value = 100 }
		land = { level = 18 value = 900 }
		naval = { level = 16 value = 600 }
	}
}

#-----------------------------------------------------------------------------------------------
