#AGCEEP - Fantasy Byzantium

#-----------------------------------------------------------------------------------------------
#Countries

include = "scenarios\1419\1419_ABK_Abkhazia.inc"
include = "scenarios\1419\1419_ADA_Adal.inc"
include = "scenarios\1419\1419_ADE_Aden.inc"
include = "scenarios\1419\1419_AKK_Ak_Koyunlu.inc"
include = "scenarios\1419\1419_ALB_Albania.inc"
include = "scenarios\1419\1419_ANG_Angoche.inc"
include = "scenarios\1419\1419_ARG_Aragon.inc"
include = "scenarios\1419\1419_ARK_Arakan.inc"
include = "scenarios\1419\1419_ASH_Ashanti.inc"
include = "scenarios\1419\1419_ATH_Athens.inc"
include = "scenarios\1419\1419_ATJ_Atjeh.inc"
include = "scenarios\1419\1419_AYU_Ayutthaya.inc"
include = "scenarios\1419\1419_AZT_Aztec_Empire.inc"
include = "scenarios\1419\1419_BAS_Basrah.inc"
include = "scenarios\1419\1419_BAY_Bavaria.inc"
include = "scenarios\1419\1419_BEI_Brunei.inc"
include = "scenarios\1419\1419_BEN_Benin.inc"
include = "scenarios\1419\1419_BGL_Bengal.inc"
include = "scenarios\1419\1419_BIM_Bima.inc"
include = "scenarios\1419\1419_BMD_Bahmanids.inc"
include = "scenarios\1419\1419_BOH_Bohemia.inc"
include = "scenarios\1419\1419_BOS_Bosnia.inc"
include = "scenarios\1419\1419_BRA_Brandenburg.inc"
include = "scenarios\1419\1419_BRE_Bremen.inc"
include = "scenarios\1419\1419_BRG_Berg.inc"
include = "scenarios\1419\1419_BRI_Brittany.inc"
include = "scenarios\1419\1419_BRM_Burma.inc"
include = "scenarios\1419\1419_BUR_Burgundy.inc"
include = "scenarios\1419\1419_BUT_Butung.inc"
include = "scenarios\1419\1419_CAM_Cambodia.inc"
include = "scenarios\1419\1419_CAN_Candar.inc"
include = "scenarios\1419\1419_CAS_Castile.inc"
include = "scenarios\1419\1419_CHA_Champa.inc"
include = "scenarios\1419\1419_CHG_Chagatai.inc"
include = "scenarios\1419\1419_CHI_China.inc"
include = "scenarios\1419\1419_CHM_Chimu.inc"
include = "scenarios\1419\1419_CLC_Calicut.inc"
include = "scenarios\1419\1419_COC_Cochin.inc"
include = "scenarios\1419\1419_CON_Connaught.inc"
include = "scenarios\1419\1419_COR_Corsica.inc"
include = "scenarios\1419\1419_CYP_Cyprus.inc"
include = "scenarios\1419\1419_DAH_Dahomey.inc"
include = "scenarios\1419\1419_DAN_Denmark.inc"
include = "scenarios\1419\1419_DAU_Dauphine.inc"
include = "scenarios\1419\1419_DES_Desmond.inc"
include = "scenarios\1419\1419_DLH_Delhi.inc"
include = "scenarios\1419\1419_DUL_Dulkadir.inc"
include = "scenarios\1419\1419_ENG_England.inc"
include = "scenarios\1419\1419_ETH_Ethiopia.inc"
include = "scenarios\1419\1419_FOI_Foix.inc"
include = "scenarios\1419\1419_FRA_France.inc"
include = "scenarios\1419\1419_FRI_Friesland.inc"
include = "scenarios\1419\1419_GEL_Guelders.inc"
include = "scenarios\1419\1419_GEN_Genoa.inc"
include = "scenarios\1419\1419_GEO_Georgia.inc"
include = "scenarios\1419\1419_GHR_Ghara.inc"
include = "scenarios\1419\1419_GON_Gondwana.inc"
include = "scenarios\1419\1419_GRA_Granada.inc"
include = "scenarios\1419\1419_GUJ_Gujarat.inc"
include = "scenarios\1419\1419_GZI_Ghazi.inc"
include = "scenarios\1419\1419_HAA_Al-Haasa.inc"
include = "scenarios\1419\1419_HAB_Austria.inc"
include = "scenarios\1419\1419_HAD_Hadramut.inc"
include = "scenarios\1419\1419_HAM_Ha_Mi.inc"
include = "scenarios\1419\1419_HAN_Hanover.inc"
include = "scenarios\1419\1419_HAS_Hausa.inc"
include = "scenarios\1419\1419_HAU_Brabant.inc"
include = "scenarios\1419\1419_HEL_Switzerland.inc"
include = "scenarios\1419\1419_HES_Hesse.inc"
include = "scenarios\1419\1419_HUN_Hungary.inc"
include = "scenarios\1419\1419_HYA_Haihaya.inc"
include = "scenarios\1419\1419_INC_Inca_Empire.inc"
include = "scenarios\1419\1419_IRA_Irak.inc"
include = "scenarios\1419\1419_JAI_Jaunpur.inc"
include = "scenarios\1419\1419_KAR_Karaman.inc"
include = "scenarios\1419\1419_KHI_Khiva.inc"
include = "scenarios\1419\1419_KIL_Kilwa.inc"
include = "scenarios\1419\1419_KLE_Cleves.inc"
include = "scenarios\1419\1419_KNI_Order_St_John.inc"
include = "scenarios\1419\1419_KOL_Cologne.inc"
include = "scenarios\1419\1419_KON_Kongo.inc"
include = "scenarios\1419\1419_KOR_Korea.inc"
include = "scenarios\1419\1419_KUT_Kutei.inc"
include = "scenarios\1419\1419_LAT_Teutonic_Order.inc"
include = "scenarios\1419\1419_LAX_Lan_Xang.inc"
include = "scenarios\1419\1419_LCH_LuChuan.inc"
include = "scenarios\1419\1419_LEI_Leinster.inc"
include = "scenarios\1419\1419_LIT_Lithuania.inc"
include = "scenarios\1419\1419_LIV_Livonian_Order.inc"
include = "scenarios\1419\1419_LNA_Lan_Na.inc"
include = "scenarios\1419\1419_LNK_Lanka.inc"
include = "scenarios\1419\1419_LOR_Lorraine.inc"
include = "scenarios\1419\1419_LUW_Luwu.inc"
include = "scenarios\1419\1419_LUX_Luxemburg.inc"
include = "scenarios\1419\1419_MAI_Mainz.inc"
include = "scenarios\1419\1419_MAL_Mali.inc"
include = "scenarios\1419\1419_MAM_Mamluks.inc"
include = "scenarios\1419\1419_MAN_Mantua.inc"
include = "scenarios\1419\1419_MAS_Masovia.inc"
include = "scenarios\1419\1419_MCH_Manchus.inc"
include = "scenarios\1419\1419_MEC_Mecklenburg.inc"
include = "scenarios\1419\1419_MEI_Meissen.inc"
include = "scenarios\1419\1419_MGL_Mongolia.inc"
include = "scenarios\1419\1419_MGU_Mogadishu.inc"
include = "scenarios\1419\1419_MKS_Makassar.inc"
include = "scenarios\1419\1419_MLC_Malacca.inc"
include = "scenarios\1419\1419_MLI_Malindi.inc"
include = "scenarios\1419\1419_MLO_Milan.inc"
include = "scenarios\1419\1419_MLW_Malwa.inc"
include = "scenarios\1419\1419_MND_Magindanao.inc"
include = "scenarios\1419\1419_MOD_Modena.inc"
include = "scenarios\1419\1419_MOL_Moldavia.inc"
include = "scenarios\1419\1419_MOM_Mombasa.inc"
include = "scenarios\1419\1419_MON_Mon.inc"
include = "scenarios\1419\1419_MOR_Morocco.inc"
include = "scenarios\1419\1419_MOS_Muscovy.inc"
include = "scenarios\1419\1419_MRA_Mahra.inc"
include = "scenarios\1419\1419_MRE_Morea.inc"
include = "scenarios\1419\1419_MSS_Mossi.inc"
include = "scenarios\1419\1419_MTR_Mataram.inc"
include = "scenarios\1419\1419_MUB_Mu_Bang.inc"
include = "scenarios\1419\1419_MYG_MengYang.inc"
include = "scenarios\1419\1419_NAP_Naples.inc"
include = "scenarios\1419\1419_NAV_Navarre.inc"
include = "scenarios\1419\1419_NIP_Japan.inc"
include = "scenarios\1419\1419_NOR_Norway.inc"
include = "scenarios\1419\1419_NUB_Nubia.inc"
include = "scenarios\1419\1419_NVG_Novgorod.inc"
include = "scenarios\1419\1419_OLD_Oldenburg.inc"
include = "scenarios\1419\1419_ORI_Orissa.inc"
include = "scenarios\1419\1419_ORM_Ormuz.inc"
include = "scenarios\1419\1419_OYO_Oyo.inc"
include = "scenarios\1419\1419_PAK_Perak.inc"
include = "scenarios\1419\1419_PAL_Palembang.inc"
include = "scenarios\1419\1419_PAP_Papal_States.inc"
include = "scenarios\1419\1419_PFA_Palatinate.inc"
include = "scenarios\1419\1419_POL_Poland.inc"
include = "scenarios\1419\1419_POM_Pomerania.inc"
include = "scenarios\1419\1419_POR_Portugal.inc"
include = "scenarios\1419\1419_PRO_Provence.inc"
include = "scenarios\1419\1419_PSK_Pskov.inc"
include = "scenarios\1419\1419_QAR_Kara_Koyunlu.inc"
include = "scenarios\1419\1419_RAJ_Rajputana.inc"
include = "scenarios\1419\1419_RAM_Ramazan.inc"
include = "scenarios\1419\1419_RYA_Ryazan.inc"
include = "scenarios\1419\1419_SAC_Saxony.inc"
include = "scenarios\1419\1419_SAV_Savoy.inc"
include = "scenarios\1419\1419_SCO_Scotland.inc"
include = "scenarios\1419\1419_SEI_Styria.inc"
include = "scenarios\1419\1419_SER_Serbia.inc"
include = "scenarios\1419\1419_SHI_Shirvan.inc"
include = "scenarios\1419\1419_SHL_Holstein.inc"
include = "scenarios\1419\1419_SIA_Siak.inc"
include = "scenarios\1419\1419_SIB_Sibir.inc"
include = "scenarios\1419\1419_SIE_Siena.inc"
include = "scenarios\1419\1419_SIN_Sindh.inc"
include = "scenarios\1419\1419_SON_Songhai.inc"
include = "scenarios\1419\1419_STE_Golden_Horde.inc"
include = "scenarios\1419\1419_STR_Strasburg.inc"
include = "scenarios\1419\1419_STT_Stettin.inc"
include = "scenarios\1419\1419_SWE_Sweden.inc"
include = "scenarios\1419\1419_TER_Ternate.inc"
include = "scenarios\1419\1419_THO_Theodoros.inc"
include = "scenarios\1419\1419_TIB_Tibet.inc"
include = "scenarios\1419\1419_TIM_Timurid_Empire.inc"
include = "scenarios\1419\1419_TLE_Tlemcen.inc"
include = "scenarios\1419\1419_TOS_Tuscany.inc"
include = "scenarios\1419\1419_TRE_Trebizond.inc"
include = "scenarios\1419\1419_TRV_Travancore.inc"
include = "scenarios\1419\1419_TUN_Tunis.inc"
include = "scenarios\1419\1419_TUR_Ottoman_Empire.inc"
include = "scenarios\1419\1419_TVE_Tver.inc"
include = "scenarios\1419\1419_TYR_Tyrol.inc"
include = "scenarios\1419\1419_ULS_Ulster.inc"
include = "scenarios\1419\1419_UZB_Uzbeks.inc"
include = "scenarios\1419\1419_VEN_Venice.inc"
include = "scenarios\1419\1419_VIJ_Vijayanagar.inc"
include = "scenarios\1419\1419_WAL_Wallachia.inc"
include = "scenarios\1419\1419_WUR_Wirtemberg.inc"
include = "scenarios\1419\1419_YEM_Yemen.inc"
include = "scenarios\1419\1419_ZAN_Zanzibar.inc"
include = "scenarios\1419\1419_ZAP_Zapotecs.inc"
include = "scenarios\1419\1419_ZIM_Zimbabwe.inc"

#-----------------------------------------------------------------------------------------------
#Alternative Countries

¤IF Alternative_Wales
include = "scenarios\1419\1419_WLS_Wales.inc"
include = "scenarios\1419\inc\1419_Provinces_Wales.inc"
¤ENDIF

#-----------------------------------------------------------------------------------------------
#Rebel factions

country = {
	tag = REB
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = { 399 }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R01
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R02
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R03
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R04
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R05
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R06
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = NDR
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = USR
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

include = "scenarios\Fantasy\Fantasy_Byzantium\BYZ_Byzantine_Empire.inc"

#-----------------------------------------------------------------------------------------------
