#Arakan

#-----------------------------------------------------------------------------------------------

country = {
	tag = ARK
	ai = "SmallTrade1.txt"
	policy = {
		aristocracy = 7
		centralization = 2
		innovative = 5
		mercantilism = 5
		offensive = 3
		land = 7
		quality = 3
		serfdom = 6
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = eastern_sunni }
	culture = { type = burmese }
	diplomacy = {
	}
	knownprovinces = {
		441 543 544 545 553 554 555 556 557 558 559 560 561 565 571 572
		653 654 655 656 657 658 659 660 661 662 663 664 665 666 667
		668 669 670 671 672 673 674 675 676 677 678 679 680 1018
		1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083
		1084 1085 1141 1142 1143 1144 1145 1146 1147 1149 1351 1356
		1357 1358 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552
		1553 1554 1555 1556 1557 1606
	}
	ownedprovinces = {
		671 672
	}
	controlledprovinces = {
		671 672
	}
	nationalprovinces = {
		556 672
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 671
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 672
		bailiff = yes
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 405 }
		name = "Arakan Army"
		location = 672
		infantry = 9000
		cavalry = 1000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 10 }
		trade = { level = 2 value = 70 }
		land = { level = 3 value = 750 }
		naval = { level = 3 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
