#Burma

#-----------------------------------------------------------------------------------------------

country = {
	tag = BRM
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhist }
	culture = { type = burmese }
	diplomacy = {
		relation = { tag = AYU value = -80 }
		relation = { tag = CAM value = 145 }
	}
	knownprovinces = {
		556 557 558 653 654 655 656 657 658 659 660 661 662 663 664 665
		666 667 668 669 670 671 672 673 674 675 676 677 678 679 680
		1018 1021 1078 1079 1080 1081 1082 1083 1084 1085 1143 1144
		1145 1146 1147 1149 1351 1356 1357 1358 1543 1544 1545
		1546 1547 1548 1549 1550 1551 1552 1553 
		1554 1555 1556 1557 1606
	}
	ownedprovinces = {
		1547 1548
	}
	controlledprovinces = {
		1547 1548
	}
	nationalprovinces = {
		671 1545 1546 1547 1557
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 1547
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1548
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 495 }
		name = "Ava Army"
		location = 1547
		infantry = 12000
		cavalry = 1000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 500 }
		trade = { level = 2 value = 70 }
		land = { level = 3 value = 50 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
