#Nubia / Funj

#-----------------------------------------------------------------------------------------------

country = {
	tag = NUB
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0.083333
	religion = { type = sunni } #from 1504 Sunni Rulers
	culture = {
		type = nubian
		type = arabic
	}
	diplomacy = { }
	knownprovinces = {
		357 743 744 745 746 747 748 749 750 751
	}
	ownedprovinces = {
		748 750 751 752
	}
	controlledprovinces = {
		748 750 751 752
	}
	nationalprovinces = {
		750 751
	}
	city = {
		fortress = { level = 1 }
		population = 1500
		location = 748
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3500
		location = 750
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 751
		bailiff = yes
	}
	city = {
		population = 1500
		location = 752
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 549 }
		name = "Nubian Army"
		location = 750
		infantry = 20000
		cavalry = 10000
		artillery = 0
	}
	technology = {
		stability = { level = -3 value = 0 }
		infra = { level = 1 value = 20 }
		trade = { level = 1 value = 20 }
		land = { level = 3 value = 50 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
