#Sibir

#-----------------------------------------------------------------------------------------------

country = {
	tag = SIB
	ai = "SmallTrade0.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = sunni }
	culture = {
		type = mongol
		type = altai
	}
	diplomacy = {
		relation = { tag = RUS value = -200.000 }
	}
	knownprovinces = {
		272 279 296 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466
		467 468 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 533 578
		1527 1528 1531 1532 1533 1534 1535 1536 1570 1571 1573 1575 1591 1592 1593 1594 1598 1599
		#Siberian corridor - North
		1572 581 583 586 588
	}
	ownedprovinces = {
		510 511 512 513 514 515 578 1570 1571 1573 1575
	}
	controlledprovinces = {
		510 511 512 513 514 515 578 1570 1571 1573 1575
	}
	nationalprovinces = {
		510 511 512 578 1570 1571 1573 1575
	}
	city = {
		fortress = { level = 1 }
		population = 1500
		location = 510
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1400
		location = 511
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 900
		location = 512
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 513
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3500
		location = 514
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 515
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 900
		location = 578
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 900
		location = 1570
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 900
		location = 1571
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 1573
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 1575
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 540 }
		name = "Western Horde"
		location = 510
		infantry = 5000
		cavalry = 20000
		artillery = 0
	}
	landunit = {
		id = { type = 9423 id = 541 }
		name = "Eastern Horde"
		location = 511
		infantry = 5000
		cavalry = 5000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 2 value = 20 }
		land = { level = 4 value = 300 }
		naval = { level = 0 value = 0 }
		group = muslim
	}
}

#-----------------------------------------------------------------------------------------------
