#Uzbeks

#-----------------------------------------------------------------------------------------------

country = {
	tag = UZB
	ai = "UZB_1510.ai"
	policy = {
		aristocracy = 8
		centralization = 7
		innovative = 2
		mercantilism = 8
		offensive = 8
		land = 9
		quality = 4
		serfdom = 7
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 300
	inflation = 0.00000
	merchants = 0.083333
	religion = { type = sunni }
	culture = { type = uzbehk }
	diplomacy = {
		relation = { tag = MOG value = -100 refusetrade = no }
		relation = { tag = PER value = -50 refusetrade = no }
		relation = { tag = KHI value = 100 }
	}
	knownprovinces = {
		272 296 357 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466
		467 468 477 498 504 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
		526 527 528 529 530 531 532 533 534 535 578 579 1527 1528 1529 1530 1531 1532 1533 1534
		1535 1536 1570 1571 1573 1591 1592 1593 1594 1598 1599
		#Siberian corridor - South
		1572 580 582 584 585 587 589
	}
	ownedprovinces = {
		1532 1534 1592 1591 1594 1598
	}
	controlledprovinces = {
		1532 1534 1591 1592 1594 1598
	}
	nationalprovinces = {
		523 524 1530 1531 1532 1534 1591 1592 1594 1599
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 1532
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 1594
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 1592
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1534
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 1598
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1591
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 576 }
		name = "Army of Bukhara"
		location = 1592
		infantry = 0
		cavalry = 20000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 0 }
		trade = { level = 2 value = 0 }
		land = { level = 4 value = 700 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
