#Bengal

#-----------------------------------------------------------------------------------------------

country = {
	tag = BGL
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = eastern_sunni }
	culture = { type = bengali }
	diplomacy = {
		relation = { tag = DLH value = -50 }
	}
	knownprovinces = {
		441 504 505 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550
		551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571
		572 573 574 575 576 671 672 1063 1065 1066 1069 1070 1071 1072 1073 1074 1078 1138 1140
		1363 1520 1521 1522 1523 1524 1525 1526 1527 1528 1531 1539 1540 1541 1542 1543 1545
		1546 1591 1592
		#Extension for Malacca
		1075 1076 1077 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		555 556 557 558 559
	}
	controlledprovinces = {
		555 556 557 558 559
	}
	nationalprovinces = {
		555 556 557 558
	}
	city = {
		fortress = { level = 2 }
		population = 100000
		location = 559
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 556
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 27000
		location = 555
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 22000
		location = 557
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 26000
		location = 558
		bailiff = yes
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 418 }
		name = "Bengal Army"
		location = 555
		infantry = 10000
		cavalry = 8000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 50 }
		trade = { level = 2 value = 550 }
		land = { level = 3 value = 0 }
		naval = { level = 3 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
