#Mongolia

#-----------------------------------------------------------------------------------------------

country = {
	tag = ASS
	ai = "Large.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 99
	inflation = 0
	merchants = 0.083333
	religion = { type = pagan }
	culture = { type = mongol }
	diplomacy = {
		relation = { tag = CHI value = -150 }
	}
	knownprovinces = {
		586 585 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608
		609 610 611 633 634 635 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658
		659 661 940 941 1018 1528 1529 1530 1531 1532 1533 1534 1539 1540 1541 1542 1543 1544 1553 1554
		1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1591 1592 1593 1594 1598 1599
		1600 1601 1602 1603 1604 1605 1606 1607 1608
	}
	ownedprovinces = {
		590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609
	}
	controlledprovinces = {
		590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609
	}
	nationalprovinces = {
		591 592 594 596 597 599 601 602 603 605 607 648 645 644
	}
	city = {
		population = 1000
		location = 590
		bailiff = yes
	}
	city = {
		population = 1700
		location = 591
		bailiff = yes
	}
	city = {
		population = 1700
		location = 592
		bailiff = yes
	}
	city = {
		population = 1000
		location = 593
		bailiff = yes
	}
	city = {
		population = 1700
		location = 594
		bailiff = yes
	}
	city = {
		population = 1000
		location = 595
		bailiff = yes
	}
	city = {
		population = 1700
		location = 596
		bailiff = yes
		capital = yes
	}
	city = {
		population = 1000
		location = 597
		bailiff = yes
	}
	City = {
		population = 1000
		location = 598
		bailiff = yes
	}
	city = {
		population = 1000
		location = 599
		bailiff = yes
	}
	city = {
		population = 1000
		location = 600
		bailiff = yes
	}
	city = {
		population = 1700
		location = 601
		bailiff = yes
	}
	city = {
		population = 1700
		location = 602
		bailiff = yes
	}
	city = {
		population = 1700
		location = 603
		bailiff = yes
	}
	city = {
		population = 1000
		location = 604
		bailiff = yes
	}
	city = {
		population = 1700
		location = 605
		bailiff = yes
	}
	city = {
		population = 1000
		location = 606
		bailiff = yes
	}
	city = {
		population = 1700
		location = 607
		bailiff = yes
	}
	city = {
		population = 1000
		location = 608
		bailiff = yes
	}
	city = {
		population = 1700
		location = 609
		bailiff = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 0 value = 20 }
		land = { level = 5 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
