#Zapotecs

#-----------------------------------------------------------------------------------------------

country = {
	tag = ZAP
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = zapotek }
	diplomacy = {
		relation = { tag = MAA value = -100 }
		relation = { tag = AZT value = -100 }
		relation = { tag = SPA value = -50 }
	}
	knownprovinces = {
		14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 436 822 1477 1478 1479
	}
	ownedprovinces = {
		30
	}
	controlledprovinces = {
		30
	}
	nationalprovinces = {
		29 30 31
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 30
		bailiff = yes
		capital = yes
	}
	technology = {
		stability = { level = 0 value = 0 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 1 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
