#Songhai

#-----------------------------------------------------------------------------------------------

country = {
	tag = SON
	ai = "Large.txt"
	policy = {
		aristocracy = 7
		centralization = 4
		innovative = 3
		mercantilism = 8
		offensive = 6
		land = 9
		quality = 4
		serfdom = 7
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 3
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = mande }
	diplomacy = {
		relation = { tag = MAL value = -50 }
		relation = { tag = HAS value = -50 }
	}
	knownprovinces = {
		791 792 793 794 795 805 806 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1595 1596 1597
	}
	ownedprovinces = {
		1487 1488 1489 1490 1491 1494 1495 1496 1497 1499 1597
	}
	controlledprovinces = {
		1487 1488 1489 1490 1491 1494 1495 1496 1497 1499 1597
	}
	nationalprovinces = {
		1487 1488 1489 1490 1491 1494 1495 1496 1497 1499 1597
	}
	city = {
		fortress = { level = 1 }
		population = 27000
		location = 1496
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 1490
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 1494
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 27000
		location = 1495
		bailiff = yes
		manufactory = luxury
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1497
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 1499
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1487
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1488
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1491
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1489
		bailiff = yes
	}
	tradingpost = {
		level = 3
		location = 1597
	}
	landunit = {
		id = { type = 9423 id = 542 }
		name = "Songhay Army"
		location = 1499
		infantry = 15000
		cavalry = 4500
		artillery = 0
	}
	technology = {
		stability = { level = 3 value = 42 }
		infra = { level = 1 value = 72 }
		trade = { level = 2 value = 570 }
		land = { level = 3 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
