#Khiva

#-----------------------------------------------------------------------------------------------

country = {
	tag = KHI
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0.00000
	merchants = 0.083333
	religion = { type = sunni }
	culture = {
		type = turkoman
		type = uzbek
	}
	diplomacy = {
		relation = { tag = UZB value = 100 }
		relation = { tag = PER value = 150 refusetrade = no }
	}
	knownprovinces = {
		272 296 357 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466 467
		468 477 498 504 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527
		528 529 530 531 532 533 534 535 579 1527 1528 1529 1530 1531 1532 1533 1534 1535 1536 1573 1591 1592 1593 1594 1598 1599
		#Siberian corridor - South
		1572 580 582 584 585 587 589
	}
	ownedprovinces = {
		519 521 523 1533 522 520 524
	}
	controlledprovinces = {
		519 521 523 1533 522 520 524
	}
	nationalprovinces = {
		521 522 523 524 1533
	}
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 519
		bailiff = yes
 	}
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 521
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 523
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1533
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 522
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 524
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 520
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 568 }
		name = "Army of Khiva"
		location = 522
		infantry = 5000
		cavalry = 5000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 300 }
		trade = { level = 2 value = 0 }
		land = { level = 4 value = 200 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
