#Japan (Nippon)

#-----------------------------------------------------------------------------------------------

country = {
	tag = NIP
	ai = "SmallTrade1.txt"
	policy = {
		aristocracy = 7
		centralization = 0
		innovative = 4
		mercantilism = 7
		offensive = 6
		land = 5
		quality = 8
		serfdom = 8
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = shinto }
	culture = { type = japanese }
	diplomacy = { }
	knownprovinces = {
		625 626 638 639 640 641 642 643 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659
		660 661 683 684 685 686 687 688 689 886 940 941 942 943 944 945 946 947 948 949 1018 1019 1020 1021 1082 1085 1087 1088 1089
		#Avoid isolation penalty
		596 664 668 670 672 673 678 679 682 1543 1545 1547 1548 1550 1552 1557 1601 1606
	}
	ownedprovinces = {
		683 684 685 686 687 688
	}
	controlledprovinces = {
		683 684 685 686 687 688
	}
	nationalprovinces = {
		683 684 685 686 687 688
	}
	city = {
		fortress = { level = 2 }
		population = 130000
		location = 685
		bailiff = yes
		manufactory = luxury
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 683
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 50000
		location = 684
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 100000
		location = 686
		capital = yes
		bailiff = yes
		manufactory = luxury
	}
	city = {
		fortress = { level = 1 }
		population = 50000
		location = 687
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 120000
		location = 688
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 498 }
		name = "Imperial Army"
		location = 685
		infantry = 50000
		cavalry = 20000
		artillery = 0
	}
	navalunit = {
		id = { type = 9423 id = 499 }
		name = "Imperial Fleet"
		location = 685
		warships = 0
		galleys = 15
		transports = 16
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 3 value = 0 }
		trade = { level = 2 value = 0 }
		land = { level = 5 value = 0 }
		naval = { level = 5 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
