#Oyo

#-----------------------------------------------------------------------------------------------

country = {
	tag = OYO
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = yorumba }
	diplomacy = { }
	knownprovinces = {
		791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502
	}
	ownedprovinces = {
		1500
	}
	controlledprovinces = {
		1500
	}
	nationalprovinces = {
		1500
	}
	city = {
		name = "Oyo"
		fortress = { level = 1 }
		population = 15000
		location = 1500
		bailiff = yes
		capital = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 70 }
		land = { level = 4 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
