#Golconda

#-----------------------------------------------------------------------------------------------

country = {
	tag = GOL
	ai = "GOL_1419.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = sunni }
	culture = { type = telugu }
	diplomacy = {
		relation = { tag = DLH value = -100 }
		relation = { tag = VIJ value = -100 }
		relation = { tag = AHM value = -50 }
		relation = { tag = BIJ value = -50 }
		relation = { tag = POR value = -80 }
	}
	knownprovinces = {
		#Indian Mainland
		441 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562
		563 564 565 566 567 568 569 570 571 572 573 574 575 576 671 672 1520 1521 1522 1523 1545 1546
		#Afghanistan
		1524 1525 1526 1527 1528 1531 1591 1592
		#Tibet
		1539 1540 1541 1542 1543
		#Indian Sea Zones
		1138 1140 1066 1069 1070 1071 1072 1073 1074 1078
		#Persian Gulf
		504 533 534 535 536 537 538 1063 1065 1363
		#Extension for Malacca
		1075 1076 1077 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		563 565 566
	}
	controlledprovinces = {
		563 565 566
	}
	nationalprovinces = {
		563 565 566
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 566
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 563
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 23000
		location = 565
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 496 }
		name = "Golconda Army"
		location = 566
		infantry = 10000
		cavalry = 3000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 50 }
		trade = { level = 2 value = 50 }
		land = { level = 3 value = 50 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
