#The Inca Empire

#-----------------------------------------------------------------------------------------------

country = {
	tag = INC
	ai = "Large.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 140
	inflation = 0
	merchants = 0.083333
	religion = { type = pagan }
	culture = { type = andean }
	diplomacy = { }
	knownprovinces = {
		160 162 163 164 165 166 167 168 169 170 171 172 173 174 187 192 193 194 219 1482 1483 1484
	}
	ownedprovinces = {
		162 163 164 165 166 167 168 169 170 171 172 173 174 192 193 194 219 1484 1482 1483
	}
	controlledprovinces = {
		162 163 164 165 166 167 168 169 170 171 172 173 174 192 193 194 219 1484 1482 1483
	}
	nationalprovinces = {
		162 163 164 165 166 167 168 169 170 171 172 173 174 192 193 194 219 1482 1483 1484
	}
	city = {
		population = 7000
		location = 162
		bailiff = yes
	}
	city = {
		population = 7000
		location = 163
		bailiff = yes
	}
	city = {
		population = 7000
		location = 164
		bailiff = yes
	}
	city = {
		population = 1000
		location = 165
		bailiff = yes
	}
	city = {
		population = 2000
		location = 166
		bailiff = yes
	}
	city = {
		population = 3000
		location = 167
		bailiff = yes
	}
	city = {
		population = 1000
		location = 168
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 169
		bailiff = yes
		barrack = yes
		manufactory = luxury
		capital = yes
	}
	city = {
		population = 1700
		location = 170
		bailiff = yes
	}
	city = {
		population = 1600
		location = 171
		bailiff = yes
	}
	city = {
		population = 1500
		location = 172
		bailiff = yes
	}
	city = {
		population = 1400
		location = 173
		bailiff = yes
	}
	city = {
		population = 1300
		location = 174
		bailiff = yes
	}
	city = {
		population = 1000
		location = 192
		bailiff = yes
	}
	city = {
		population = 2000
		location = 193
		bailiff = yes
	}
	city = {
		population = 2000
		location = 194
		bailiff = yes
	}
	city = {
		population = 1500
		location = 219
		bailiff = yes
	}
	city = {
		population = 4000
		location = 1482
		bailiff = yes
	}
	city = {
		population = 700
		location = 1483
		bailiff = yes
	}
	city = {
		population = 1000
		location = 1484
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 464 }
		name = "Imperial Army"
		location = 169
		infantry = 30000
		cavalry = 0
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 1 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
