#Kongo

#-----------------------------------------------------------------------------------------------

country = {
	tag = KON
	ai = "Large.ai"
	monarchtable = "scenarios\1520\monarchs\monarchs_kon.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = catholic }
	culture = { type = kongolese }
	diplomacy = {
		relation = { tag = POR value = 25 }
		relation = { tag = PAP value = 50 }
	}
	knownprovinces = {
		399 441 762 766 785 786 787 788 789 793 1503 1504 1505 1506
	}
	ownedprovinces = {
		785 786 787 1505 1506
	}
	controlledprovinces = {
		785 786 787 1505 1506
	}
	nationalprovinces = {
		785 786 787 1505 1506
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 1506
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1505
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 786
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 787
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 785
		bailiff = yes
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 472 }
		name = "Jungle Army"
		location = 1506
		infantry = 10000
		cavalry = 0
		artillery = 0
	}
	technology = {
		stability = { level = 3 value = 42 }
		infra = { level = 1 value = 450 }
		trade = { level = 1 value = 120 }
		land = { level = 4 value = 50 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
