#Ethiopia

#-----------------------------------------------------------------------------------------------

country = {
	tag = ETH
	ai = "Large.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = miaphysite }
	culture = { type = ethiopian }
	diplomacy = {
		relation = { tag = ADA value = -150 }
	}
	knownprovinces = {
		743 744 745 746 747 748 749 750 751 752 753 754 755 757 758 759 760 761 1516 1517 1518 1519 1059 1060 1061 1062 1588 1589 1590
	}
	ownedprovinces = {
		753 1516 1517 1588 1589 1590
	}
	controlledprovinces = {
		753 1516 1517 1588 1589 1590
	}
	nationalprovinces = {
		752 753 758 1516 1517 1518 1519 1588 1589 1590
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		bailiff = yes
		location = 753
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1517
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1516
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1588
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1589
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1590
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 442 }
		name = "Royal Army"
		location = 1517
		infantry = 10000
		cavalry = 2000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 70 }
		land = { level = 3 value = 750 }
		naval = { level = 0 value = 50 }
	}
}

#-----------------------------------------------------------------------------------------------
