#Vijayanagar

#-----------------------------------------------------------------------------------------------

country = {
	tag = VIJ
	ai = "SmallTrade1.ai"
	policy = {
		aristocracy = 7
		centralization = 5
		innovative = 4
		mercantilism = 10
		offensive = 6
		land = 5
		quality = 3
		serfdom = 7
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 154
	inflation = 0
	merchants = 0.083333
	religion = { type = hinduism }
	culture = {
		type = dravidian
		type = cambodian
		type = lithuanian
	}
	diplomacy = {
		relation = { tag = HYD value = -100 }
		relation = { tag = AHM value = -100 }
		relation = { tag = DAM value = -100 }
		relation = { tag = POR value = 50 }
	}
	knownprovinces = {
		441 504 505 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550
		551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571
		572 573 574 575 576 671 672 1063 1065 1066 1069 1070 1071 1072 1073 1074 1078 1138 1140
		1363 1520 1521 1522 1523 1524 1525 1526 1527 1528 1531 1539 1540 1541 1542 1543 1545
		1546 1591 1592
		#Extension for Malacca
		1075 1076 1077 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		567 568 570 571 572 575
	}
	controlledprovinces = {
		567 568 570 571 572 575
	}
	nationalprovinces = {
		565 567 571
	}
	city = {
		fortress = { level = 1 }
		population = 50000
		location = 567
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 40000
		location = 570
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 24000
		location = 571
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 13000
		location = 572
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 13000
		location = 575
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 568
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 580 }
		name = "Vijayanagar Army"
		location = 567
		infantry = 15000
		cavalry = 6000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 550 }
		trade = { level = 3 value = 550 }
		land = { level = 3 value = 0 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
