#Benin

#-----------------------------------------------------------------------------------------------

country = {
	tag = BEN
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = yoruba }
	diplomacy = {
		relation = { tag = POR value = 150 }
	}
	knownprovinces = {
		441 791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502
	}
	ownedprovinces = {
		791 792
	}
	controlledprovinces = {
		791 792
	}
	nationalprovinces = {
		792
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 791
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 792
		bailiff = yes
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 417 }
		name = "Benin Army"
		location = 792
		infantry = 12000
		cavalry = 1500
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 70 }
		land = { level = 2 value = 150 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
