#Tibet

#-----------------------------------------------------------------------------------------------

country = {
	tag = TIB
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = { type = tibetan }
	diplomacy = {
	}
	knownprovinces = {
		543 544 554 555 556 559 649 1539 1540 1541 1542 1543 1544 1545 1546 1547 1548 1549 1550
		1551 1552 1553 1554 1555 1556 1557 1558 1559 1560 1563 1603 1604 1605 1606 1607 1608
	}
	ownedprovinces = {
		1539 1540 1541 1542 1543
	}
	controlledprovinces = {
		1539 1540 1541 1542 1543
	}
	nationalprovinces = {
		1539 1540 1541 1542 1543 1544 1605 1607
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1543
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 1539
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 1540
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1541
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1542
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 556 }
		name = "Tibetan Army"
		location = 1543
		infantry = 10000
		cavalry = 2000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 100 }
		trade = { level = 2 value = 70 }
		land = { level = 3 value = 50 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
