#Kilwa

#-----------------------------------------------------------------------------------------------

country = {
	tag = KIE
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 50
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = swahili }
	diplomacy = {
		relation = { tag = POR value = -70 }
		relation = { tag = ZUL value = 50 refusetrade = no }
		relation = { tag = ARM value = -75 refusetrade = no }
		relation = { tag = DEL value = 25 refusetrade = no }
	}
	knownprovinces = {
		441 489 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 532 533 534 536 537 538
		539 541 547 756 757 759 760 761 762 763 764 765 766 767 768 769 770 771 1059 1060 1061 1062 1063
		1064 1065 1066 1067 1068 1069 1070 1071 1133 1134 1135 1136 1138 1185 1186 1512 1513 1514 1515 1359 1363 1510 1511 1592
	}
	ownedprovinces = {
		764 766
	}
	controlledprovinces = {
		764 766
	}
	nationalprovinces = {
		764 765 766 767
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 764
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 766
		bailiff = yes
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 8560 }
		name = "Army of Zanj"
		location = 766
		infantry = 5000
		cavalry = 2000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 70 }
		land = { level = 3 value = 50 }
		naval = { level = 2 value = 90 }
	}
}

#-----------------------------------------------------------------------------------------------
