#Hausa

#-----------------------------------------------------------------------------------------------

country = {
	tag = HAS
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = yoruba }
	diplomacy = {
		relation = { tag = SON value = -50 }
	}
	knownprovinces = {
		744 791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 
		1499 1500 1501 1502 1595 
	}
	ownedprovinces = {
		1501 1502
	}
	controlledprovinces = {
		1501 1502
	}
	nationalprovinces = {
		1499 1501
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 1501
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1502
		bailiff = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 70 }
		land = { level = 4 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
