#Rajputana

#-----------------------------------------------------------------------------------------------

country = {
	tag = JAI
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = hinduism }
	culture = { type = aleutian }
	diplomacy = {
		relation = { tag = DLH value = -100 }
	}
	knownprovinces = {
		504 505 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551
		552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572
		573 574 575 576 671 672 1063 1065 1066 1069 1070 1071 1072 1073 1074 1078 1138 1140
		1363 1520 1521 1522 1523 1524 1525 1526 1527 1528 1531 1539 1540 1541 1542 1543 1545
		1546 1591 1592
	}
	ownedprovinces = {
		1522 542
	}
	controlledprovinces = {
		1522 542
	}
	nationalprovinces = {
		542 543 546 1522
	}
	city = {
		fortress = { level = 1 }
		population = 40000
		location = 542
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 1522
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 465 }
		name = "Jodhpur Army"
		location = 542
		infantry = 6000
		cavalry = 10000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 0 }
		trade = { level = 3 value = 0 }
		land = { level = 3 value = 0 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
