#Mon

#-----------------------------------------------------------------------------------------------

country = {
	tag = PEG
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = { type = burmese }
	diplomacy = { }
	knownprovinces = {
		543 544 545 553 554 555 556 557 558 559 560 561 565 571 572
		653 654 655 656 657 658 659 660 661 662 663 664 665 666 667
		668 669 670 671 672 673 674 675 676 677 678 679 680 1018
		1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083
		1084 1085 1141 1142 1143 1144 1145 1146 1147 1149 1351 1356
		1357 1358 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553
		1554 1555 1556
	}
	ownedprovinces = {
		673
	}
	controlledprovinces = {
		673
	}
	nationalprovinces = {
		673
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 673
		capital = yes
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 508 }
		name = "Pegu Army"
		location = 673
		infantry = 12000
		cavalry = 1000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 2 value = 10 }
		trade = { level = 2 value = 70 }
		land = { level = 2 value = 550 }
		naval = { level = 2 value = 200 }
	}
}

#-----------------------------------------------------------------------------------------------
