#Sultanate of Delhi

#-----------------------------------------------------------------------------------------------

country = {
	tag = DLH
	ai = "DLH_1419.ai"
	policy = {
		aristocracy = 8
		centralization = 1
		innovative = 4
		mercantilism = 6
		offensive = 6
		land = 8
		quality = 6
		serfdom = 6
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = sunni }
	culture = { type = afghani }
	diplomacy = {
		relation = { tag = MOG value = -100 refusetrade = no }
		relation = { tag = GUJ value = -100 }
		relation = { tag = BGL value = -50 }
		relation = { tag = JAI value = -100 }
		relation = { tag = DAM value = -100 }
		relation = { tag = HYD value = -100 }
		relation = { tag = AHM value = -100 }
	}
	knownprovinces = {
		441 504 505 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 
		551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 
		572 573 574 575 576 671 672 1063 1065 1066 1069 1070 1071 1072 1073 1074 1078 1138 1140 
		1363 1520 1521 1522 1523 1524 1525 1526 1527 1528 1531 1539 1540 1541 1542 1543 1545 
		1546 1591 1592 
	}
	ownedprovinces = {
		543 544 545 553 554 1520 1521 1523
	}
	controlledprovinces = {
		543 544 545 553 554 1520 1521 1523
	}
	nationalprovinces = {
		543 544 545 553 554 1520 1521
	}
	city = {
		fortress = { level = 1 }
		population = 120000
		location = 543
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 40000
		location = 545
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 100000
		location = 544
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 553
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 22000
		location = 554
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 30000
		location = 1520
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 26000
		location = 1521
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 1523
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 434 }
		name = "Delhi Army"
		location = 543
		infantry = 5000
		cavalry = 10000
		artillery = 0
	}
	technology = {
		stability = { level = -3 value = 42 }
		infra = { level = 2 value = 0 }
		trade = { level = 2 value = 0 }
		land = { level = 3 value = 550 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
