#Aztec Empire

#-----------------------------------------------------------------------------------------------

country = {
	tag = AZT
	ai = "AZT_1419.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = pagan }
	culture = { type = aztek }
	diplomacy = {
		relation = { tag = MAA value = -100 }
		relation = { tag = ZAP value = -100 }
		relation = { tag = SPA value = -200 }
	}
	knownprovinces = {
		14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 436 822 1477 1478 1479
	}
	ownedprovinces = {
		24 25 26 27 28 31
	}
	controlledprovinces = {
		24 25 26 27 28 31
	}
	nationalprovinces = {
		24 25 26 27 28
	}
	city = {
		population = 1000
		location = 24
		bailiff = yes
	}
	city = {
		population = 1000
		location = 25
		bailiff = yes
	}
	city = {
		population = 1000
		location = 26
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 27
		bailiff = yes
		capital = yes
	}
	city = {
		population = 1000
		location = 28
		bailiff = yes
	}
	city = {
		population = 1000
		location = 31
		bailiff = yes
	}
	technology = {
		stability = { level = -3 value = 0 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 1 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
