#Angoche

#-----------------------------------------------------------------------------------------------

country = {
	tag = ANG
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = swahili }
	diplomacy = { }
	knownprovinces = {
		489 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 532 533 534 536 537
		538 539 541 547 569 756 757 759 760 761 762 763 764 765 766 767 768 769 770 771 1059 1060
		1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1133 1134 1135 1136 1138 1184 1185
		1186 1512 1513 1514 1515 1359 1363 1592
	}
	ownedprovinces = {
		769
	}
	controlledprovinces = {
		769
	}
	nationalprovinces = {
		769
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 769
		bailiff = yes
		capital = yes
	}
	technology = {
		stability = { level = -1 value = 42 }
		infra = { level = 1 value = 10 }
		trade = { level = 2 value = 70 }
		land = { level = 3 value = 50 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
