#Dahomey

#-----------------------------------------------------------------------------------------------

country = {
	tag = DAH
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = aka }
	diplomacy = { }
	knownprovinces = {
		791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502
	}
	ownedprovinces = {
		1498 793 794
	}
	controlledprovinces = {
		1498 793 794
	}
	nationalprovinces = {
		794 1498 793
	}
	city = {
		fortress = { level = 1 }
		population = 28000
		location = 1498
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 793
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 9000
		location = 794
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 428 }
		name = "Royal Army"
		location = 1498
		infantry = 12000
		cavalry = 0
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 70 }
		land = { level = 1 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
