#Mataram

#-----------------------------------------------------------------------------------------------

country = {
	tag = MTR
	ai = "SmallTrade1.txt"
	policy = {
		aristocracy = 8
		centralization = 4
		innovative = 4
		mercantilism = 5
		offensive = 8
		land = 3
		quality = 6
		serfdom = 6
	}
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = eastern_sunni }
	culture = { type = javan }
	diplomacy = {
		relation = { tag = MLC value = 175 }
		relation = { tag = PAL value = 125 }
		relation = { tag = PAK value = 175 }
		relation = { tag = ATJ value = 175 }
	}
	knownprovinces = {
		441 556 557 558 653 654 655 656 657 658 659 660 661 662 663 664 665
		666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681
		682 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709
		710 711 1018 1078 1079 1080 1081 1082 1083 1084 1085 1086 1087
		1143 1144 1145 1146 1147 1148 1149 1150 1205 1206 1207 1208
		1209 1210 1211 1213 1214 1215 1216 1221 1222 1345 1346 1347
		1348 1349 1350 1351 1352 1353 1354 1355 1356 1357 1358 1544
		1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
	}
	ownedprovinces = {
		702 703 704
	}
	controlledprovinces = {
		702 703 704
	}
	nationalprovinces = {
		701 702 703 704
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 702
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 703
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 704
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 492 }
		name = "Mataram Army"
		location = 704
		infantry = 5000
		cavalry = 1000
		artillery = 0
	}
	navalunit = {
		id = { type = 9423 id = 493 }
		name = "Mataram Fleet"
		location = 704
		warships = 0
		galleys = 5
		transports = 5
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 10 }
		trade = { level = 2 value = 70 }
		land = { level = 3 value = 450 }
		naval = { level = 2 value = 100 }
	}
}

#-----------------------------------------------------------------------------------------------
