#Dai Viet

#-----------------------------------------------------------------------------------------------

country = {
	tag = DAI
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = confucian }
	culture = { type = vietnamese }
	diplomacy = {
		relation = { tag = CAM value = -70 }
	}
	knownprovinces = {
		441 556 557 558 641 642 649 650 652 653 654 655 656 657 658 659 660
		661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676
		677 678 679 680 685 686 687 688 940 941 942 944 1018 1019 1020
		1021 1078 1079 1080 1081 1082 1083 1084 1085 1143 1144 1145
		1146 1147 1149 1351 1356 1357 1358 1544 1545 1546 1547 1548
		1549 1550 1551 1552 1553 1554 1555 1556
	}
	ownedprovinces = {
		662 663 664 665 1554
	}
	controlledprovinces = {
		662 663 664 665 1554
	}
	nationalprovinces = {
		662 663 664 665 1554
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 662
		bailiff = yes
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7500
		location = 663
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7500
		location = 1554
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 664
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 665
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 429 }
		name = "Dai Viet Army"
		location = 662
		infantry = 20000
		cavalry = 5000
		artillery = 0
	}
	technology = {
		stability = { level = -3 value = 42 }
		infra = { level = 2 value = 10 }
		trade = { level = 3 value = 70 }
		land = { level = 3 value = 50 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
