#Kazakhs

#-----------------------------------------------------------------------------------------------

country = {
	tag = KZK
	ai = "SmallTrade0.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 250
	inflation = 0.00000
	merchants = 0.083333
	religion = { type = sunni }
	culture = { type = kazakh }
	diplomacy = { }
	knownprovinces = {
		272 296 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466 467 468 510
		511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 533 1527 1528 1531 1532 1533
		1534 1535 1536 1591 1592 1593 1594 1598 1599
		#Siberian corridor - South
		1572 580 582 584 585 587 589
	}
	ownedprovinces = {
		516 1535 1536 579 518 517
	}
	controlledprovinces = {
		516 1535 1536 579 518 517
	}
	nationalprovinces = {
		516 1534 1535 1536 517 518 579
	}
	city = {
		fortress = { level = 1 }
		population = 4500
		location = 516
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1535
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 1536
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 517
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 518
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 579
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 474 }
		name = "Kazakh Horde"
		location = 1536
		infantry = 0
		cavalry = 20000
		artillery = 0
	}

	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 4 value = 400 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
