#Malindi

#-----------------------------------------------------------------------------------------------

country = {
	tag = MLI
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = swahili }
	diplomacy = {
		relation = { tag = MOM value = -150 refusetrade = no }
		relation = { tag = KIL value = -75 refusetrade = no }
		relation = { tag = MGU value = 25 refusetrade = no }
		relation = { tag = POR value = 100 refusetrade = no }
	}
	knownprovinces = {
		441 489 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 532 533 534 536
		537 538 539 541 547 756 757 759 760 761 762 763 764 765 766 767 1059 1060 1061 1062 1063
		1064 1065 1066 1067 1068 1069 1070 1071 1133 1134 1135 1136 1138 1185 1186 1512 1513 1514 1515 1359 1363 1592
	}
	ownedprovinces = {
		761 762
	}
	controlledprovinces = {
		761 762
	}
	nationalprovinces = {
		761 762
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 761
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 762
		bailiff = yes
		capital = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 0 value = 70 }
		land = { level = 3 value = 50 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
