#The Inca Empire

#-----------------------------------------------------------------------------------------------

country = {
	tag = INC
	ai = "Large.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 140
	inflation = 0
	merchants = 0.083333
	religion = { type = pagan }
	culture = { type = andean }
	diplomacy = {
		relation = { tag = CHM value = 150 refusetrade = no }
	}
	knownprovinces = {
		160 162 163 164 165 166 167 168 169 170 171 172 173 174 187 192 193 194 219 1482 1483 1484
	}
	ownedprovinces = {
		167 168 169 170 171 172 173 174 192 193 194 219 1484
	}
	controlledprovinces = {
		167 168 169 170 171 172 173 174 192 193 194 219 1484
	}
	nationalprovinces = {
		162 163 164 165 166 167 168 169 170 171 172 173 174 192 193 194 219 1482 1483 1484
	}
	city = {
		fortress = { level = 1 }
		population = 30000
		location = 169
		capital = yes
		bailiff = yes
	}
	city = {
		population = 1000
		location = 192
	}
	city = {
		population = 1000
		location = 1484
	}
	city = {
		population = 3000
		location = 167
	}
	city = {
		population = 1000
		location = 168
	}
	city = {
		population = 1700
		location = 170
	}
	city = {
		population = 1600
		location = 171
	}
	city = {
		population = 1500
		location = 172
	}
	city = {
		population = 1400
		location = 173
	}
	city = {
		population = 1300
		location = 174
	}
	city = {
		population = 2000
		location = 193
	}
	city = {
		population = 2000
		location = 194
	}
	city = {
		population = 1500
		location = 219
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
