#Rajput

#-----------------------------------------------------------------------------------------------

country = {
	tag = JAI
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 120
	inflation = 0
	merchants = 0.083333
	religion = { type = hinduism }
	culture = { type = aleutian } #Rajput
	diplomacy = {
		relation = { tag = DLH value = 25 }
		relation = { tag = GUJ value = 5 }
		relation = { tag = MLW value = 125 access = yes }
	}
	knownprovinces = {
		#Indian Mainland
		539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
		562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 671 672 1520 1521 1522 1523 1545 1546
		#Afghanistan
		1524 1525 1526 1527 1528 1531 1591 1592
		#Tibet
		1539 1540 1541 1542 1543
		#Indian Sea Zones
		1138 1140 1066 1069 1070 1071 1072 1073 1074 1078
		#Persian Gulf
		505 533 534 535 536 537 538 1063 1065 1363
	}
	ownedprovinces = {
		542 1522
	}
	controlledprovinces = {
		542 1522
	}
	nationalprovinces = {
		542 546 1522
	}
	city = {
		fortress = { level = 1 }
		population = 40000
		location = 542
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 1522
	}
	landunit = {
		id = { type = 9424 id = 9001 }
		name = "Rajputanian Army"
		location = 542
		infantry = 4000
		cavalry = 7000
		artillery = 0
	}
	technology = {
		stability = { level = 1 value = 2 }
		infra = { level = 0 value = 40 }
		trade = { level = 0 value = 200 }
		land = { level = 1 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
