#Ha Mi

#-----------------------------------------------------------------------------------------------

country = {
	tag = HAM
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 50
	inflation = 0.100000
	merchants = 0.083333
	religion = { type = confucian }
	culture = {
		type = uighur
	}
	diplomacy = {
		relation = { tag = CHI value = 100 }
	}
	knownprovinces = {
		272 296 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466 467 468 510
		511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 533 596 597 599 601 602 603
		649 653 1527 1528 1531 1532 1533 1534 1535 1536 1539 1540 1541 1542 1543 1544 1559 1591 1592
		1593 1594 1598 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608
	}
	ownedprovinces = {
		1606
	}
	controlledprovinces = {
		1606
	}
	nationalprovinces = {
		1606
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1606
	}
	landunit = {
		id = { type = 6001 id = 229 }
		name = "Ha Mi Army"
		location = 1606
		infantry = 5000
		cavalry = 5000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 50 }
		trade = { level = 0 value = 50 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
