#Adal

#-----------------------------------------------------------------------------------------------

country = {
	tag = CYR
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = {
		type = somali
		type = ethiopian
	}
	diplomacy = { }
	knownprovinces = {
		743 744 745 746 747 748 749 750 751 752 753 754 755 757 758 759 760 761 1516 1517 1518 1519 1588 1589 1590
	}
	ownedprovinces = {
		754 755 758 1518 1519
	}
	controlledprovinces = {
		754 755 758 1518 1519
	}
	nationalprovinces = {
		754 755 758 1517 1518 1519
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 754
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1500
		location = 755
	}
	city = {
		fortress = { level = 1 }
		population = 300
		location = 758
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1518
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1519
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
