#Uzbeks

#-----------------------------------------------------------------------------------------------

country = {
	tag = UZB
	ai = "UZB_1419_Default.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 50
	inflation = 0.000000
	merchants = 0.083333
	religion = { type = sunni}
	culture = { type = naskapi }
	diplomacy = {
		relation = { tag = SIB value = 150 refusetrade = no }
		relation = { tag = STE value = 150 refusetrade = no }
		relation = { tag = KHI value = 0 refusetrade = no }
	}
	knownprovinces = {
		446 447 451 452 453 454 455 456 457 458 459 466 467 468 510 511 512 513 514 515 516 517
		518 519 520 521 522 523 524 525 526 578 579 1527 1528 1531 1532 1533 1534 1535 1536 1571 1570 1573 1591 1592 1593 1594 1598 1599
		#Siberian corridor - South
		1572 580 582 584 585 587 589
	}
	ownedprovinces = {
		1534 1535 516 1536 517 579 518 520 519
	}
	controlledprovinces = {
		1534 1535 516 1536 517 579 518 520 519
	}
	nationalprovinces = {
		1534 1535 516 1536 517 579 518 520
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 1536
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 520
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 1534
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 1535
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 516
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 517
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 518
	}
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 579
	}
	city = {
		population = 1000
		location = 519
	}
	landunit = {
		id = { type = 6001 id = 214 }
		name = "Khan's Guard"
		location = 1536
		infantry = 0
		cavalry = 7000
		artillery = 0
	}
	technology = {
		stability = { level = 1 value = 50 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 20 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
