#Kongo

#-----------------------------------------------------------------------------------------------

country = {
	tag = KON
	ai = "Large.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = kongolese }
	diplomacy = { }
	knownprovinces = {
		766 785 786 787 1505 1506
	}
	ownedprovinces = {
		785 786 787 1505 1506
	}
	controlledprovinces = {
		785 786 787 1505 1506
	}
	nationalprovinces = {
		785 786 787 1505 1506
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1506
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1505
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 786
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 787
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 785
		capital = yes
	}
	technology = {
		stability = { level = 3 value = 42 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
