#Khwarazim (not playable)

#-----------------------------------------------------------------------------------------------

country = {
	tag = KHI
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 0
	inflation = 0.000000
	merchants = 0.083333
	religion = { type = sunni }
	culture = { type = turkoman }
	diplomacy = {
		relation = { tag = TIM value = 0 refusetrade = no }
		relation = { tag = UZB value = 0 refusetrade = no }
	}
	knownprovinces = {
		515 516 518 519 520 521 522 523 524 1532 1533 1534 1535 1594
	}
	ownedprovinces = {
		521 522 1533
	}
	controlledprovinces = {
		521 522 1533
	}
	nationalprovinces = { }
	city = {
		population = 3000
		location = 1533
		capital = yes
	}
	city = {
		population = 3000
		location = 522
	}
	city = {
		population = 800
		location = 521
	}
	technology = {
		stability = { level = 0 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
