#Lan Na

#-----------------------------------------------------------------------------------------------

country = {
	tag = KHM
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = { type = thai }
	diplomacy = {
		relation = { tag = ARK value = 75 }
		relation = { tag = CAM value = 75 }
		relation = { tag = CHA value = 75 }
		relation = { tag = CHI value = 75 }
		relation = { tag = DAI value = 75 }
		relation = { tag = MLC value = 75 }
		relation = { tag = TAU value = 25 }
		relation = { tag = AYU value = 25 }
		relation = { tag = MYA value = 25 }
		relation = { tag = PEG value = 25 }
		relation = { tag = AMI value = 25 }
	}
	knownprovinces = {
		556 557 558 653 654 655 656 657 658 659 660 661 662 663 664 665
		666 667 668 669 670 671 672 673 674 675 676 677 678 679 680
		1018 1021 1078 1079 1080 1081 1082 1083 1084 1085 1143 1144
		1145 1146 1147 1149 1351 1356 1357 1358 1543 1544 1545
		1546 1547 1548 1549 1550 1551 1552 1553 
		1554 1555 1556 1557 1606
	}
	ownedprovinces = {
		1549 1550
	}
	controlledprovinces = {
		1549 1550
	}
	nationalprovinces = {
		1549 1550
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1549
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1550
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 840 }
		name = "La Na Army"
		location = 1550
		infantry = 6000
		cavalry = 2000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 1 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
