#Nubia

#-----------------------------------------------------------------------------------------------

country = {
	tag = NUB
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0.083333
	religion = { type = miaphysite }
	culture = { type = nubian }
	diplomacy = { }
	knownprovinces = {
		357 743 744 745 746 747 748 749 750 751
	}
	ownedprovinces = {
		750 751
	}
	controlledprovinces = {
		750 751
	}
	nationalprovinces = {
		750 751
	}
	city = {
		fortress = { level = 1 }
		population = 3500
		location = 750
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 751
	}
	landunit = {
		id = { type = 9423 id = 964 }
		name = "Nubian Army"
		location = 750
		infantry = 5000
		cavalry = 5000
		artillery = 0
	}
	technology = {
		stability = { level = -2 value = 42 }
		infra = { level = 1 value = 20 }
		trade = { level = 1 value = 20 }
		land = { level = 1 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
