#The Chimú Empire

#-----------------------------------------------------------------------------------------------

country = {
	tag = CHM
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 140
	inflation = 0
	merchants = 0.083333
	religion = { type = pagan }
	culture = { type = andean }
	diplomacy = {
		relation = { tag = INC value = 150 refusetrade = no }
	}
	knownprovinces = {
		160 162 163 164 165 166 167 168 169 170 171 172 173 174 187 192 193 194 219 1482 1483 1484
	}
	ownedprovinces = {
		162 163 164 165 166 1482 1483
	}
	controlledprovinces = {
		162 163 164 165 166 1482 1483
	}
	nationalprovinces = {
		162 163 164 165 166 1482 1483
	}
	city = {
		fortress = { level = 1 }
		population = 14000
		location = 165
		capital = yes
		bailiff = yes
	}
	city = {
		population = 7000
		location = 164
	}
	city = {
		population = 1000
		location = 1482
	}
	city = {
		population = 2000
		location = 166
	}
	city = {
		population = 7000
		location = 162
	}
	city = {
		population = 7000
		location = 163
	}
	city = {
		population = 1000
		location = 1483
	}
	technology = {
		stability = { level = 0 value = 42 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
