#Burma

#-----------------------------------------------------------------------------------------------

country = {
	tag = MYA
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = { type = burmese }
	diplomacy = {
		relation = { tag = CHI value = 40 }
		relation = { tag = ARK value = 170 }
		relation = { tag = BGL value = 75 }
		relation = { tag = PEG value = 65 }
		relation = { tag = TAU value = 40 }
		relation = { tag = KHM value = 25 }
		relation = { tag = AYU value = 75 }
	}
	knownprovinces = {
		556 557 558 653 654 655 656 657 658 659 660 661 662 663 664 665
		666 667 668 669 670 671 672 673 674 675 676 677 678 679 680
		1018 1021 1078 1079 1080 1081 1082 1083 1084 1085 1143 1144
		1145 1146 1147 1149 1351 1356 1357 1358 1543 1544 1545
		1546 1547 1548 1549 1550 1551 1552 1553 
		1554 1555 1556 1557 1606
	}
	ownedprovinces = {
		671 1546 1547
	}
	controlledprovinces = {
		671 1546 1547
	}
	nationalprovinces = {
		671 1546 1547
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1546
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 671
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 1547
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 837 }
		name = "Burmese Army"
		location = 1547
		infantry = 10000
		cavalry = 3000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
