#Sibir

#-----------------------------------------------------------------------------------------------

country = {
	tag = SIB
	ai = "SmallTrade0.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 50
	inflation = 0
	merchants = 0.083333
	religion = { type = sunni }
	culture = {
		type = altai
	}
	diplomacy = {
		relation = { tag = TIM value = -75 refusetrade = no }
		relation = { tag = STE value = 75 refusetrade = no }
		relation = { tag = UZB value = 150 refusetrade = no }
	}
	knownprovinces = {
		446 447 451 452 453 454 455 456 457 458 459 466 467 468 510 511 512 513 514 515 516 517 518
		519 520 521 522 523 524 525 526 578 1527 1528 1531 1532 1533 1534 1535 1536 1570 1571 1573 1575 1591 1592 1593 1594 1598 1599
		#Siberian corridor - North
		1572 581 583 586 588
	}
	ownedprovinces = {
		1575
	}
	controlledprovinces = {
		1575
	}
	nationalprovinces = {
		1575
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 1575
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 951 }
		name = "On's Guard"
		location = 1575
		infantry = 0
		cavalry = 3000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 20 }
		trade = { level = 0 value = 20 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
