#Bahmanid Empire

#-----------------------------------------------------------------------------------------------

country = {
	tag = BMD
	ai = "BMD_1419.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = eastern_sunni }
	culture = {
		type = telugu
		type = marathi
	}
	diplomacy = {
		relation = { tag = GUJ value = -50 }
	}
	knownprovinces = {
		#Indian Mainland
		539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562
		563 564 565 566 567 568 569 570 571 572 573 574 575 576 671 672 1520 1521 1522 1523 1545 1546
		#Afghanistan
		1524 1525 1526 1527 1528 1531 1591 1592
		#Tibet
		1539 1540 1541 1542 1543
		#Indian Sea Zones
		1138 1140 1066 1069 1070 1071 1072 1073 1074 1078
		#Persian Gulf
		505 533 534 535 536 537 538 1063 1065 1363
		#Extension for Malacca
		1075 1076 1077 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		550 551 563 566 548
	}
	controlledprovinces = {
		550 551 563 566 548
	}
	nationalprovinces = {
		550 551 565 566
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 548
	}
	city = {
		fortress = { level = 1 }
		population = 19000
		location = 550
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 551
	}
	city = {
		population = 22000
		location = 563
	}
	city = {
		fortress = { level = 1 }
		population = 30000
		location = 566
		capital = yes
		bailiff = yes
	}
	landunit = {
		id = { type = 9423 id = 821 }
		name = "Gulbarga Army"
		location = 566
		infantry = 15000
		cavalry = 6000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 80 }
		trade = { level = 1 value = 0 }
		land = { level = 0 value = 100 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
