#Al-Haasa

#-----------------------------------------------------------------------------------------------

country = {
	tag = HAA
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = shia }
	culture = { type = arabic }
	diplomacy = {
		relation = { tag = ORM value = 125 }
		relation = { tag = HAD value = 125 }
		relation = { tag = ADE value = 125 }
		relation = { tag = MRA value = 125 }
		relation = { tag = GHR value = 125 }
		relation = { tag = YEM value = 125 }
		relation = { tag = QAR value = 125 }
		relation = { tag = MGU value = 125 }
		relation = { tag = CAN value = 125 }
		relation = { tag = KAR value = 125 }
		relation = { tag = MAM value = 125 }
		relation = { tag = GZI value = 125 }
		relation = { tag = GUJ value = 125 }
		relation = { tag = ADA value = 125 }
		relation = { tag = SHI value = 125 }
		relation = { tag = TUR value = 125 }
		relation = { tag = AKK value = 125 }
		relation = { tag = IRA value = 125 }
		relation = { tag = BAS value = 125 }
		relation = { tag = TIM value = 75 refusetrade = no }
	}
	knownprovinces = {
		357 358 359 360 441 470 471 472 473 474 475 476 477 478 479 480
		481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496
		497 498 499 500 501 502 503 504 505 506 507 508 509 525 526 527
		528 529 530 531 532 533 534 535 536 537 538 539 540 541 547 568
		741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756
		757 759 760 820 997 1002 1003 1004 1005 1006 1007 1008 1009 1010
		1011 1012 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069
		1070 1071 1134 1135 1136 1331 1359 1363 1525 1526 1529 1530 1592
		1609 1610 1611 1613
	}
	ownedprovinces = {
		506 507
	}
	controlledprovinces = {
		506 507
	}
	nationalprovinces = {
		506 507
	}
	city = {
		fortress = { level = 1 }
		population = 2500
		location = 506
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1500
		location = 507
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
