#Arakan

#-----------------------------------------------------------------------------------------------

country = {
	tag = ARK
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = { type = burmese }
	diplomacy = {
		relation = { tag = KHM value = 75 }
		relation = { tag = PEG value = 65 }
		relation = { tag = MYA value = 175 }
	}
	knownprovinces = {
		Bengal
		#543 544 545 553 554 555 556 557 558 559 560 561 565 571 572
		653 #Ming
		#654 655 656 657 658 659 660 661 662 663 664 665 666 667
		#668 669 670 671 672 
		673 674 
		#675 676 677 678 679 680 1018
		#1072 1073 1074 1075 1076 1077 
		1078 
		#1079 1080 1081 1082 1083
		#1084 1085 1141 1142 1143 1144 1145 1146 1147 1149 1351 1356
		#1357 1358 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552
		#1553 1554 1555 1556 1557 1606
	}
	ownedprovinces = {
		672
	}
	controlledprovinces = {
		672
	}
	nationalprovinces = {
		
	}
	claimedprovinces = {
		672
		}

	city = {
		fortress = { level = 1 }
		population = 20000
		location = 672
		capital = yes
	}
	landunit = {
		id = { type = 9497 id = 835 }
		name = "Arakanese Army"
		location = 672
		infantry = 9000
		cavalry = 1000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
