#Travancore

#-----------------------------------------------------------------------------------------------

country = {
	tag = TAN
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = hinduism }
	culture = { type = lithuanian }
	diplomacy = {
		relation = { tag = VIJ value = 125 }
	}
	knownprovinces = {
		539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562
		563 564 565 566 567 568 569 570 571 572 573 574 575 576 671 672 1520 1521 1522 1523 504 505 506
		507 508 509 533 534 535 536 537 538 1531 1069 1070 1071 1138 1140 1068 1136 1135 1064 1065 1066
		1067 1063 1363
		#Extension for Malacca
		1075 1076 1077 1078 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		574
	}
	controlledprovinces = {
		574
	}
	nationalprovinces = {
		574
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 574
		capital = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 50 }
		trade = { level = 0 value = 50 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
