#Songhai

#-----------------------------------------------------------------------------------------------

country = {
	tag = SON
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = mali }
	diplomacy = {
		relation = { tag = OYO value = 25 }
		relation = { tag = HAS value = 25 }
		relation = { tag = DAH value = 25 }
		relation = { tag = MAL value = 25 }
		relation = { tag = MOR value = -100 }
		relation = { tag = MSS value = 75 }
		relation = { tag = ASH value = 25 }
	}
	knownprovinces = {
		791 792 793 794 805 806 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1595 1596 1597
	}
	ownedprovinces = {
		1496 1497
	}
	controlledprovinces = {
		1496 1497
	}
	nationalprovinces = {
		1496 1497
	}
	city = {
		fortress = { level = 1 }
		population = 18000
		location = 1496
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1497
	}
	technology = {
		stability = { level = 3 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
