#Majapahit Empire/Java

#-----------------------------------------------------------------------------------------------

country = {
	tag = MTR
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = hinduism }
	culture = { type = javan }
	diplomacy = { }
	knownprovinces = {
		556 557 558 653 654 655 656 657 658 659 660 661 662 663 664 665
		666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681
		682 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709
		710 711 1018 1078 1079 1080 1081 1082 1083 1084 1085 1086 1087
		1143 1144 1145 1146 1147 1148 1149 1150 1205 1206 1207 1208
		1209 1210 1211 1213 1214 1215 1216 1221 1222 1345 1346 1347
		1348 1349 1350 1351 1352 1353 1354 1355 1356 1357 1358 1544
		1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
	}
	ownedprovinces = {
		698 701 702 703 704 705
	}
	controlledprovinces = {
		698 701 702 703 704 705
	}
	nationalprovinces = {
		701 702 703 704
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 698
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 701
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 702
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 703
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 704
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 705
	}
	landunit = {
		id = { type = 6001 id = 231 }
		name = "Javan Army"
		location = 703
		infantry = 10000
		cavalry = 2000
		artillery = 0
	}
	landunit = {
		id = { type = 6001 id = 1514 }
		name = "Bali Army"
		location = 705
		infantry = 5000
		cavalry = 100
		artillery = 0
	}
	landunit = {
		id = { type = 6001 id = 1500 }
		name = "Banjarmasin Army"
		location = 698
		infantry = 3000
		cavalry = 200
		artillery = 0
	}
	navalunit = {
		id = { type = 6001 id = 232 }
		name = "Javan Fleet"
		location = 702
		warships = 0
		galleys = 10
		transports = 5
	}
	technology = {
		stability = { level = 2 value = 0 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 100 }
	}
}

#-----------------------------------------------------------------------------------------------
