#China (Chung Kuo)

#-----------------------------------------------------------------------------------------------

country = {
	tag = CHI
	ai = "CHI_1419_ZengHe.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 500
	inflation = 0.4
	merchants = 0.083333
	religion = { type = confucian }
	culture = {
		type = han
		type = zhuang
	}
	diplomacy = {
		relation = { tag = KOR value = 50 guaranteed = { year = 1500 month = january day = 1 } }
		relation = { tag = HAM value = 100 access = yes guaranteed = { year = 1450 month = january day = 1 } }
		relation = { tag = TIB value = 50 guaranteed = { year = 1450 month = january day = 1 } }
		relation = { tag = LNA value = 40 }
		relation = { tag = CHA value = 40 }
		relation = { tag = BRM value = 40 }
		relation = { tag = MUB value = 40 }
		relation = { tag = LCH value = 0 guaranteed = { year = 1420 month = january day = 1 } }
		relation = { tag = MGL value = -25 }
		relation = { tag = MCH value = 25 }
	}
	knownprovinces = {
		596 599 601 603 605 607 627 629 625 626 628 634 635 636 637 638 639 640 641 642 643 644 645 646 647
		648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 685 686 687 688 689 940
		941 942 943 944 1018 1019 1020 1021 1081 1082 1083 1084 1085 1086 1087 1088 1145 1146 1147 1149 1150
		1151 1152 1207 1349 1350 1351 1352 1356 1544 1545 1546 1553 1554 1555 1556 1557 1558 1559 1560 1561
		1562 1563 1564 1565 1566 1567
		#Tibet
		1542 1543 1605 1606 1607
		#Bit of Burma
		1547 1548 1549 1550
		#Laos
		669 1551 1552
		#Ayutthaya
		670 674 675
		#Cambodia
		667 668
		#The Silk Road
		1592 1598 1599 1600 1601 1602 1603 1604 1608
		#Malaysia Indonesia India
		541 543 545 547 558 559 560 561 563 569 571 573 574 575 576 577 672 673 676 677 678 679 680 681 682 695 696 697 698 702 703 704 705 1074 1068 1069 1070 1071 1072 1078 1079 1080 1138 1140 1141 1143 1205 1208 1389 1347 1353 1357 1523 1524 1527 1591
	}
	ownedprovinces = {
		646 1608 662 663 1554
		647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 1553 1555 1556 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567
	}
	controlledprovinces = {
		646 1608 662 663 1554
		647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 1553 1555 1556 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567
	}
	nationalprovinces = {
		1608
		646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 1553 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567
	}
	city = {
		fortress = { level = 1 }
		population = 11000
		location = 650
	}
	city = {
		population = 10000
		location = 660
	}
	city = {
		fortress = { level = 1 }
		population = 35000
		location = 661
	}
	city = {
		fortress = { level = 1 }
		population = 65000
		location = 659
	}
	city = {
		population = 25000
		location = 658
	}
	city = {
		fortress = { level = 1 }
		population = 80000
		location = 657
	}
	city = {
		fortress = { level = 1 }
		population = 60000
		location = 656
	}
	city = {
		fortress = { level = 1 }
		population = 100000
		location = 655
	}
	city = {
		fortress = { level = 1 }
		population = 70000
		location = 654
	}
	city = {
		fortress = { level = 2 }
		population = 180000
		location = 653
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 150000
		location = 652
	}
	city = {
		fortress = { level = 1 }
		population = 50000
		location = 651
	}
	city = {
		fortress = { level = 1 }
		population = 160000
		location = 649
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 647
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 648
	}
	city = {
		fortress = { level = 1 }
		population = 55000
		location = 646
	}
	city = {
		population = 15000
		location = 1559
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1560
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 1561
	}
	city = {
		population = 10000
		location = 1553
	}
	city = {
		fortress = { level = 1 }
		population = 80000
		location = 1558
	}
	city = {
		fortress = { level = 1 }
		population = 55000
		location = 1556
	}
	city = {
		fortress = { level = 1 }
		population = 200000
		location = 1563
	}
	city = {
		fortress = { level = 1 }
		population = 80000
		location = 1562
	}
	city = {
		population = 30000
		location = 1566
	}
	city = {
		fortress = { level = 1 }
		population = 200000
		location = 1564
	}
	city = {
		fortress = { level = 1 }
		population = 110000
		location = 1565
	}
	city = {
		fortress = { level = 1 }
		population = 160000
		location = 1567
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 1555
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 1608
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 662
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 663
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1554
	}
	landunit = {
		id = { type = 9423 id = 995 }
		name = "Imperial Army"
		location = 649
		infantry = 10000
		cavalry = 5000
		artillery = 0
	}
	landunit = {
		id = { type = 9423 id = 989 }
		name = "Kai Ping Army"
		location = 648
		infantry = 10000
		cavalry = 5000
		artillery = 0
	}
	landunit = {
		id = { type = 9423 id = 997 }
		name = "Da Tong Army"
		location = 1561
		historicalleader = {
			id = { type = 6 id = 032319 }
			category = general
			name = "Liu Sheng"
			startdate = {
				year = 1408
			}
			deathdate = {
				year = 1431
			}
			rank = 5
			movement = 2
			fire = 4
			shock = 1
			siege = 0
			remark = "Military contributions in the first invasion of An Nam, subsequently participated in other campaigns, including the northern expeditions against the Mongols. He was experienced in using gunpowder weapons. Ordered to pacify An Nam again in the sixth month of Xuan De year 2 (May AD 1427), but was ambushed by Le Loi and killed."
		}
		infantry = 11000
		cavalry = 7000
		artillery = 0
	}
	landunit = {
		id = { type = 9423 id = 998 }
		name = "Gan Su Army"
		location = 1559
		infantry = 12000
		cavalry = 4000
		artillery = 0
	}
	landunit = {
		id = { type = 9423 id = 996 }
		name = "Yun Nan Army"
		location = 1556
		historicalleader = {
			id = { type = 6 id = 032320 }
			category = general
			name = "Mu Sheng"
			startdate = {
				year = 1398
				month = june
			}
			deathdate = {
				year = 1439
				month = february
			}
			rank = 2
			movement = 3
			fire = 3
			shock = 2
			siege = 0
			location = 1556
			remark = "Second son of the famous Empire founding general Mu Ying, inherited the nobility from his father and brother. Appointed as Duke of Qian after conquest of An Nam. Not skilled in warfare, record of failure in many battles, but the imperial administration was lenient to him because he guarded the remote Yun Nan province, and the Mu family had built up a strong reputation amongst Yun Nan tribes. He died in the army during the retreat from a defeat in the Lu Chuan campaign in the Yun Nan province."
		}
		infantry = 16000
		cavalry = 4000
		artillery = 0
	}
	landunit = {
		id = { type = 9423 id = 988 }
		name = "Jiao Zhi Army 1"
		location = 662
		historicalleader = {
			id = { type = 6 id = 032321 }
			category = general
			name = "Li Bin"
			startdate = {
				year = 1403
				month = may
			}
			deathdate = {
				year = 1422
				month = february
			}
			rank = 4
			movement = 3
			fire = 4
			shock = 3
			siege = 0
			location = 662
			remark = "Military contributions during Cheng Zu's revolt against his nephew to sieze the throne. Replaced Zhang Fu in commanding Ming forces in Jiao Zhi. During his leadership he was at least able to get the rebellion under some control. His successors failed to do this."
		}
		infantry = 14000
		cavalry = 5000
		artillery = 0
	}
	landunit = {
		id = { type = 9423 id = 991 }
		name = "Jiao Zhi Army 2"
		location = 1554
		historicalleader = {
			id = { type = 6 id = 032322 }
			category = general
			name = "Fang Zheng"
			startdate = {
				year = 1409
			}
			deathdate = {
				year = 1440
			}
			rank = 5
			movement = 3
			fire = 3
			shock = 2
			siege = 0
			location = 662
			remark = "A general who participated in many major campaigns such as pacifying An Nam and later in the Lu Chuan campaign in Yun Nan. But his record was not good. Conflict with another general Chen Zhi resulted in his failure in pacifying An Nam. He was also at odds with Mu Cheng in the Lu Chuan campaign, and was killed during the campaign on Zheng Tong year 4, month 1, day 3 (17th January, 1439) during an ambush by the enemy when he was trying to pursue enemy forces."
		}
		infantry = 13000
		cavalry = 4000
		artillery = 0
	}
	navalunit = {
		id = { type = 9424 id = 992 }
		name = "Treasure Fleet"
		location = 1069
		historicalleader = {
			id = { type = 6 id = 032323 }
			category = explorer
			startdate = {
				year = 1405
			}
			deathdate = {
				year = 1436
			}
			name = "Zheng He"
			rank = 2
			movement = 6
			fire = 3
			shock = 3
			siege = 0
			dormant = no
		}
		warships = 1
		galleys = 0
		transports = 0
	}
	navalunit = {
		id = { type = 9424 id = 993 }
		name = "Treasure Fleet"
		location = 1069
		warships = 49
		galleys = 0
		transports = 50
	}
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 1 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 1 value = 0 }
		naval = { level = 5 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
