#Zimbabwe

#-----------------------------------------------------------------------------------------------

country = {
	tag = ZIM
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = shona }
	diplomacy = { }
	knownprovinces = {
		766 770 771 772 1507 1508 1509 1510 1511
	}
	ownedprovinces = {
		1507 1508 1509 1510 1511
	}
	controlledprovinces = {
		1507 1508 1509 1510 1511
	}
	nationalprovinces = {
		771 772 1507 1508 1509 1510 1511
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1509
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1507
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1508
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1510
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1511
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
