#Kilwa

#-----------------------------------------------------------------------------------------------

country = {
	tag = KIE
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = swahili }
	diplomacy = {
		relation = { tag = ARM value = 155 refusetrade = no }
		relation = { tag = DEL value = 155 refusetrade = no }
		relation = { tag = ZUL value = 155 refusetrade = no }
		relation = { tag = ZAN value = 125 refusetrade = no }
		relation = { tag = ANH value = 125 refusetrade = no }
	}
	knownprovinces = {
		498 499 500 501 502 503 504 505 506 534 536 537
		538 539 541 547 756 757 759 760 761 762 763 764 765 766 767 768 769 770 1060
		1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1133 1134 1135 1136 1138
		1184 1185 1186 1187 1188 1189 1253 1255 1324 1325 1359 1508 1511 1512 1513 1514 1515 1592
  	}
	ownedprovinces = {
		764 766 767 770
	}
	controlledprovinces = {
		764 766 767 770
	}
	nationalprovinces = {
		764 766 767
	}
	city = {
		fortress = { level = 1 }
		population = 100
		location = 764
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 766
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1500
		location = 767
	}
	tradingpost = {
		level = 3
		location = 770
	}
	landunit = {
		id = { type = 9423 id = 8560 }
		name = "Army of Zanj"
		location = 766
		infantry = 5000
		cavalry = 2000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 1 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 90 }
	}
}

#-----------------------------------------------------------------------------------------------
