#Vijayanagar

#-----------------------------------------------------------------------------------------------

country = {
	tag = VIJ
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = hinduism }
	culture = {
		type = dravidian
		type = cambodian
		type = lithuanian
	}
	diplomacy = {
		relation = { tag = SYR value = 5 }
		relation = { tag = NAF value = 5 }
	}
	knownprovinces = {
		#Indian Mainland
		539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562
		563 564 565 566 567 568 569 570 571 572 573 574 575 576 671 672 1520 1521 1522 1523 1545 1546
		#Afghanistan
		1524 1525 1526 1527 1528 1531 1591 1592
		#Tibet
		1539 1540 1541 1542 1543
		#Indian Sea Zones
		1138 1140 1066 1069 1070 1071 1072 1073 1074 1078
		#Persian Gulf
		505 533 534 535 536 537 538 1063 1065 1363
		#Extension for Malacca
		1075 1076 1077 1079 1080 1141 1143 677
	}
	ownedprovinces = {
		567 570 571 572 575 568 549
	}
	controlledprovinces = {
		567 570 571 572 575 568 549
	}
	nationalprovinces = {
		567 571
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 549
	}
	city = {
		fortress = { level = 1 }
		population = 26000
		location = 567
		capital = yes
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 568
	}
	city = {
		fortress = { level = 1 }
		population = 30000
		location = 570
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 571
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 572
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 575
	}
	landunit = {
		id = { type = 9423 id = 822 }
		name = "Vijayanagar Army"
		location = 567
		infantry = 15000
		cavalry = 6000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 1 value = 50 }
		trade = { level = 1 value = 50 }
		land = { level = 1 value = 0 }
		naval = { level = 1 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
