#Lan Xang

#-----------------------------------------------------------------------------------------------

country = {
	tag = LAX
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhist }
	culture = { type = thai }
	diplomacy = {
		relation = { tag = LNA value = 25 }
		relation = { tag = AYU value = 100 }
		relation = { tag = DAI value = 95 }
		relation = { tag = CAM value = 100 }
	}
	knownprovinces = {
		#SE Asia Mainland
		556 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679 1546 1547 1548 1549 1550 1551 1552 1554
		#SE Asia Sea Zones
		940 941 1018 1078 1079 1080 1081 1082 1083 1085 1143 1145 1146 1351 1356
		#Little bit of China
		649 650 652 653 655 656 657 658 659 660 661 1545 1553 1555 1556 1557
		#Korea
		641 642
		#Nippon
		683 684 685 686 687 688 944 1019
		#Little bit of India
		555 557 558 559
	}
	ownedprovinces = {
		669 1552 1551
	}
	controlledprovinces = {
		669 1552 1551
	}
	nationalprovinces = {
		669 1552 1551
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 669
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1552
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1551
	}
	landunit = {
		id = { type = 9423 id = 830 }
		name = "Vientiane Army"
		location = 1552
		infantry = 10000
		cavalry = 2000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
