#Gondwana

#-----------------------------------------------------------------------------------------------

country = {
	tag = GON
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 120
	inflation = 0
	merchants = 0.083333
	religion = { type = hindu }
	culture = { type = hindi }
	diplomacy = {
		relation = { tag = DLH value = 25 }
		relation = { tag = VIJ value = 5 }
		relation = { tag = HYA value = 5 }
		relation = { tag = ORI value = 5 }
	}
	knownprovinces = {
		543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 566 565 567
		568 569 570 571 572 573 574 575 576 577
	}
	ownedprovinces = {
		552
	}
	controlledprovinces = {
		552
	}
	nationalprovinces = {
		552
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 552
		capital = yes
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 40 }
		trade = { level = 1 value = 0 }
		land = { level = 0 value = 200 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
