#Tibet

#-----------------------------------------------------------------------------------------------

country = {
	tag = TIB
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = buddhism }
	culture = { type = tibetan }
	diplomacy = { }
	knownprovinces = {
		1547 1548 1549 1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 1560 1563 1603 1604 1605 1606 1607 1608
		543 544 554 555 556 559 649 1539 1540 1541 1542 1543 1544 1545 1546
	}
	ownedprovinces = {
		1605 1544 1607
		1539 1540 1541 1542 1543
	}
	controlledprovinces = {
		1605 1544 1607
		1539 1540 1541 1542 1543
	}
	nationalprovinces = {
		1605 1544 1607
		1539 1540 1541 1542 1543
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1543
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 1539
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 1540
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1541
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1542
	}
	city = {
		population = 4000
		location = 1605
	}
	city = {
		population = 3000
		location = 1544
	}
	city = {
		population = 4000
		location = 1607
	}
	landunit = {
		id = { type = 9423 id = 847 }
		name = "Tibetan Army"
		location = 1543
		infantry = 10000
		cavalry = 200
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
