#Ashanti

#-----------------------------------------------------------------------------------------------

country = {
	tag = ASH
	ai = "SmallTrade1.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = ashanti }
	diplomacy = {
		relation = { tag = SON value = 25 }
		relation = { tag = DAH value = 75 }
	}
	knownprovinces = {
		#791 792 793 
		794 
		#1487 1488 1489 
		1490 
		#1491 
		1492 1493 1494 1495 
		#1496 1497 
		1498 
		#1499 1500 1501 1502
	}
	ownedprovinces = {
		1493
	}
	controlledprovinces = {
		1493
	}
	nationalprovinces = {
			}
	claimedprovinces = {
		795 1493
		}
	city = {
		fortress = { level = 1 }
		population = 28000
		location = 1493
		capital = yes
	}
	technology = {
		stability = { level = 3 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
n