#Manchu Empire (Manchuria)

#-----------------------------------------------------------------------------------------------

country = {
	tag = MCH
	ai = "Large.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 300
	inflation = 0
	merchants = 0
	religion = { type = confucian }
	culture = {
		type = manchu
	}
	diplomacy = { }
	knownprovinces = {
		624 627 628 629 630 631 632 633 634 662 1467 1468 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1606 1608
		625 626 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659
		660 661 683 684 685 686 687 688 689 886 940 941 942 943 944 945 946 947 948 949 1018 1019 1020 1021 1085 1087 1088
		#Avoid isolation penalty
		596 664 668 670 672 673 678 679 682 1543 1545 1547 1548 1550 1552 1557 1601
	}
	ownedprovinces = {
		625 626 627 628 634
		635 636 637 638 639 640 643 644 645
	}
	controlledprovinces = {
		625 626 627 628 634
		635 636 637 638 639 640 643 644 645
	}
	nationalprovinces = {	
		 639 640 643 
	}
	claimedprovinces = {
		625 626 627 628 634 635 636 637 638 644
	}
	city = {
		population = 3000
		location = 625
	}
	city = {
		population = 5000
		location = 626
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 627
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 628
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 634
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 643
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 30000
		location = 635
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 644
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 645
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 640
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 639
	}
	city = {
		fortress = { level = 1 }
		population = 15000
		location = 636
	}
	city = {
		population = 3000
		location = 638
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 637
	}
	landunit = {
		id = { type = 9423 id = 846 }
		name = "Manchurian Army"
		location = 643
		infantry = 20000
		cavalry = 15000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 1 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
