#Šhirvan

#-----------------------------------------------------------------------------------------------

country = {
	tag = SHI
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 50
	inflation = 0.000000
	merchants = 0.083333
	religion = { type = sunni }
	culture = {
		type = caucasian
		type = turkish
	}
	diplomacy = {
		relation = { tag = AKK value = 150 }
		relation = { tag = GEO value = 150 }
		relation = { tag = STE value = 75 refusetrade = no }
	}
	knownprovinces = {
		457 458 465 466 467 468 469 470 471 472 473 474 475 485 486 487 488 489 490 508 529 530 531 532 533 534
		1016 1017 1326 1327 1530 1531 1592
	}
	ownedprovinces = {
		471
	}
	controlledprovinces = {
		471
	}
	nationalprovinces = {
		471
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 471
		capital = yes
	}
	diplomats = 1
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 1 value = 0 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
