#Ethiopia

#-----------------------------------------------------------------------------------------------

country = {
	tag = ETH
	ai = "Large.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = orthodox }
	culture = { type = ethiopian }
	diplomacy = {
	}
	knownprovinces = {
		743 744 745 746 747 748 749 750 751 752 753 754 755 757 758 759 760 761 1516 1517 1518 1519 1059 1060 1061 1062 1588 1589 1590
	}
	ownedprovinces = {
		752 753 1516 1517 1588 1589 1590
	}
	controlledprovinces = {
		752 753 1516 1517 1588 1589 1590
	}
	nationalprovinces = {
		752 753 758 1516 1517 1518 1519 1588 1589 1590
	}
	city = {
		fortress = { level = 1 }
		population = 1000
		location = 752
	}
	city = {
		fortress = { level = 1 }
		population = 4000
		location = 753
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 1517
		capital = yes
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 1516
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1588
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1589
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 1590
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
