#Mogadishu

#-----------------------------------------------------------------------------------------------

country = {
	tag = MGU
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = {
		type = swahili
		type = somali
	}
	diplomacy = {
		relation = { tag = MLI value = 170 refusetrade = no }
		relation = { tag = KIL value = 170 refusetrade = no }
		relation = { tag = MOM value = 170 refusetrade = no }
	}
	knownprovinces = {
		441 489 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 532 533 534 536 537
		538 539 541 547 756 757 759 760 761 762 763 764 765 766 767 1059 1060 1061 1062 1063 1064 1065
		1066 1067 1068 1069 1070 1071 1133 1134 1135 1136 1138 1185 1186 1512 1513 1514 1515 1359 1363
		1592
	}
	ownedprovinces = {
		757 759 760
	}
	controlledprovinces = {
		757 759 760
	}
	nationalprovinces = {
		757 759 760
	}
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 757
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 759
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		capital = yes
		location = 760
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
