#Chagatai Khanate

#-----------------------------------------------------------------------------------------------

country = {
	tag = CHG
	ai = "Large.ai"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 150
	inflation = 0.100000
	merchants = 0.083333
	religion = { type = sunni }
	culture = {
		type = hawaiian #Uighur
	}
	diplomacy = { }
	knownprovinces = {
		Kazakhstan
		#272 296 446 447 448 449 451 452 453 454 455 456 457 
		458 
		#459 460 461 462 463 466 467 468
		#510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 533 
		596
		#649 
		653 
		#1527 1528
		1531 
		#1532 1533 1534 1535 
		1536 
		#1539 1540 1541 1542 
		1543 
		#1544 1559 1591 
		1592 
		#1593 1594 1598
		#1599 1600 1601 1602 1603 1604 1605 1606 1607 1608
	}
	ownedprovinces = {
		1600 1601 1602 1603 1604
	}
	controlledprovinces = {
		1600 1601 1602 1603 1604
	}
	nationalprovinces = {
			}
	claimedprovinces = {
		1598 1599 1600 1601 1602 1603 1604 1606
	}
	city = {
		population = 4000
		location = 1600
	}
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 1601
		capital = yes
	}
	city = {
		population = 5000
		location = 1602
	}
	city = {
		population = 5000
		location = 1603
	}
	city = {
		population = 5000
		location = 1604
	}
	landunit = {
		id = { type = 6001 id = 230 }
		name = "Chagatai Horde"
		location = 1601
		infantry = 0
		cavalry = 20000
		artillery = 0
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 0 value = 50 }
		trade = { level = 0 value = 50 }
		land = { level = 0 value = 50 }
		naval = { level = 0 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
