#Events for the reformation mod - by Alun

#-----------------------------------------------------------------------------------------------

event = "Events\RNGC\Reformation\RNGC_Main.eue"
event = "Events\RNGC\Reformation\Protestant_Britain.eue"
event = "Events\RNGC\Reformation\Protestant_Germany.eue"
event = "Events\RNGC\Reformation\Protestant_Lowlands.eue"
event = "Events\RNGC\Reformation\Protestant_Other.eue"
event = "Events\RNGC\Reformation\Protestant_Scandinavia.eue"
event = "Events\RNGC\Reformation\Reformed_Britain.eue"
event = "Events\RNGC\Reformation\Reformed_France.eue"
event = "Events\RNGC\Reformation\Reformed_Germany.eue"
event = "Events\RNGC\Reformation\Reformed_Lowlands.eue"
event = "Events\RNGC\Reformation\Reformed_Other.eue"
event = "Events\RNGC\Reformation\RNGC_Protestant_Britain.eue"
event = "Events\RNGC\Reformation\RNGC_Protestant_Lowlands.eue"
event = "Events\RNGC\Reformation\RNGC_Protestant_Germany.eue"
event = "Events\RNGC\Reformation\RNGC_Protestant_Other.eue"
event = "Events\RNGC\Reformation\RNGC_Protestant_Scandinavia.eue"
event = "Events\RNGC\Reformation\RNGC_Reformed_Britain.eue"
event = "Events\RNGC\Reformation\RNGC_Reformed_France.eue"
event = "Events\RNGC\Reformation\RNGC_Reformed_Germany.eue"
event = "Events\RNGC\Reformation\RNGC_Reformed_Lowlands.eue"
event = "Events\RNGC\Reformation\RNGC_Reformed_Other.eue"

#-----------------------------------------------------------------------------------------------
