#The Reformation

#-----------------------------------------------------------------------------------------------
#Provinces

province = { id = 236 religion = reformed }	#The Highlands
province = { id = 237 religion = reformed }	#The Grampians
province = { id = 238 religion = reformed }	#Lothian
province = { id = 239 religion = reformed }	#Strathclyde
province = { id = 240 religion = protestant }	#Northumberland
province = { id = 241 religion = protestant }	#Yorkshire
province = { id = 242 religion = protestant }	#Lancashire
province = { id = 243 religion = protestant }	#Wales
province = { id = 244 religion = reformed }	#Midlands
province = { id = 245 religion = protestant }	#Lincoln
province = { id = 246 religion = protestant }	#Bristol
province = { id = 247 religion = protestant }	#Anglia
province = { id = 248 religion = protestant }	#Kent
province = { id = 249 religion = protestant }	#Wessex
province = { id = 250 religion = protestant }	#Cornwall
province = { id = 251 religion = protestant }	#Skåne
province = { id = 252 religion = protestant }	#Småland
province = { id = 253 religion = protestant }	#Västergötland
province = { id = 254 religion = protestant }	#Svealand
province = { id = 255 religion = protestant }	#Østlandet
province = { id = 256 religion = protestant }	#Bergenshus
province = { id = 257 religion = protestant }	#Bergslagen
province = { id = 258 religion = protestant }	#Trøndelag
province = { id = 259 religion = protestant }	#Narvik
province = { id = 260 religion = protestant }	#Lappland
province = { id = 261 religion = protestant }	#Finnmark
province = { id = 263 religion = protestant }	#Österbotten
province = { id = 264 religion = protestant }	#Tavastland
province = { id = 265 religion = protestant }	#Nyland
province = { id = 273 religion = protestant }	#Savolaks
province = { id = 276 religion = protestant }	#Estland
province = { id = 282 religion = protestant }	#Livland
province = { id = 283 religion = protestant }	#Kurland
province = { id = 289 religion = protestant }	#Memel
province = { id = 290 religion = protestant }	#Prussia
province = { id = 301 religion = protestant }	#Danzig
province = { id = 302 religion = protestant }	#Hinterpommern
province = { id = 303 religion = protestant }	#Poznan
province = { id = 304 religion = protestant }	#Vorpommern
province = { id = 305 religion = protestant }	#Mecklenburg
province = { id = 306 religion = protestant }	#Holstein
province = { id = 307 religion = protestant }	#Sjælland
province = { id = 308 religion = protestant }	#Gotland
province = { id = 309 religion = protestant }	#Jylland
province = { id = 310 religion = protestant }	#Hannover
province = { id = 311 religion = protestant }	#Magdeburg
province = { id = 312 religion = protestant }	#Brandenburg
province = { id = 313 religion = protestant }	#Küstrin
province = { id = 314 religion = protestant }	#Silesia
province = { id = 317 religion = reformed }	#Ruthenia
province = { id = 323 religion = protestant }	#Transylvania
province = { id = 324 religion = reformed }	#Maros
province = { id = 325 religion = reformed }	#Magyar
province = { id = 328 religion = protestant }	#Bohemia
province = { id = 329 religion = protestant }	#Erz
province = { id = 323 religion = protestant }	#Sudeten
province = { id = 331 religion = protestant }	#Sachsen
province = { id = 332 religion = protestant }	#Anhalt
province = { id = 333 religion = reformed }	#Hessen
province = { id = 335 religion = protestant }	#Oldenburg
province = { id = 336 religion = reformed }	#Bremen
province = { id = 337 religion = reformed }	#Friesen
province = { id = 338 religion = reformed }	#Geldre
province = { id = 339 religion = reformed }	#Holland
province = { id = 340 religion = reformed }	#Zeeland
province = { id = 341 religion = protestant }	#Västerbotten
province = { id = 342 religion = protestant }	#Finland
province = { id = 345 religion = reformed }	#Pfalz
province = { id = 346 religion = reformed }	#Mainz
province = { id = 347 religion = protestant }	#Würzburg
province = { id = 354 religion = protestant }	#Banat
province = { id = 372 religion = protestant }	#Württemberg
province = { id = 380 religion = reformed }	#Flandern
province = { id = 381 religion = protestant }	#Jämtland
province = { id = 388 religion = reformed }	#Bern
province = { id = 407 religion = reformed }	#Dauphiné
province = { id = 412 religion = reformed }	#Maine
province = { id = 418 religion = reformed }	#Poitou
province = { id = 419 religion = reformed }	#Limousin
province = { id = 421 religion = reformed }	#Cévennes
province = { id = 422 religion = reformed }	#Languedoc
province = { id = 423 religion = reformed }	#Guyenne
province = { id = 425 religion = reformed }	#Béarn
province = { id = 1469 religion = protestant }	#Gästrikland
province = { id = 1612 religion = reformed }	#Schwyz

#-----------------------------------------------------------------------------------------------
