#Random Number Genarator Country

#-----------------------------------------------------------------------------------------------

country = {
	tag = MUS
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	policy = {
		date = { year = 0 month = january day = 0 }
		aristocracy = 0
		centralization = 0
		innovative = 10
		mercantilism = 10
		offensive = 5
		land = 10
		quality = 5
		serfdom = 5
	}
	merchants = 0.0
	religion = { type = pagan }
	culture = { type = scandinavian }
	diplomacy = { }
	knownprovinces = { 1614 }
	ownedprovinces = { 1614 }
	controlledprovinces = { 1614 }
	nationalprovinces = { 1614 }
	city = {
		population = 2000
		location = 1614
		name = "Fortuna"
		capital = yes
	}
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = exotic
	}
}

#-----------------------------------------------------------------------------------------------
