#AGCEEP - 1648 Scenario

#-----------------------------------------------------------------------------------------------
#Countries

include = "scenarios\1648\1648_AMI_Lan_Xang.inc"
include = "scenarios\1648\1648_ANH_Angoche.inc"
include = "scenarios\1648\1648_ANN_Annam.inc"
include = "scenarios\1648\1648_ARK_Arakan.inc"
include = "scenarios\1648\1648_ARM_Malindi.inc"
include = "scenarios\1648\1648_ASH_Ashanti.inc"
include = "scenarios\1648\1648_ATJ_Atjeh.inc"
include = "scenarios\1648\1648_AUV_Magindanao.inc"
include = "scenarios\1648\1648_AYU_Ayutthaya.inc"
include = "scenarios\1648\1648_BAY_Bavaria.inc"
include = "scenarios\1648\1648_BAL_Baluchistan.inc"
include = "scenarios\1648\1648_BEI_Brunei.inc"
include = "scenarios\1648\1648_BEN_Benin.inc"
include = "scenarios\1648\1648_BGL_Bengal.inc"
include = "scenarios\1648\1648_BJR_Banjar.inc"
include = "scenarios\1648\1648_BLI_Bali.inc"
include = "scenarios\1648\1648_BRA_Brandenburg.inc"
include = "scenarios\1648\1648_BTM_Bantam.inc"
include = "scenarios\1648\1648_BUK_Bukhara.inc"
include = "scenarios\1648\1648_BUT_Butung.inc"
include = "scenarios\1648\1648_CAM_Cambodia.inc"
include = "scenarios\1648\1648_CHG_Chagatai.inc"
include = "scenarios\1648\1648_CHI_China.inc"
include = "scenarios\1648\1648_CRI_Crimea.inc"
include = "scenarios\1648\1648_CYR_Adal.inc"
include = "scenarios\1648\1648_DAH_Dahomey.inc"
include = "scenarios\1648\1648_DAI_Dai_Viet.inc"
include = "scenarios\1648\1648_DAN_Denmark.inc"
include = "scenarios\1648\1648_DAS_Da_Shun.inc"
include = "scenarios\1648\1648_DAX_Da_Xi.inc"
include = "scenarios\1648\1648_DEL_Mogadishu.inc"
include = "scenarios\1648\1648_EDE_Madurai.inc"
include = "scenarios\1648\1648_EIR_Ireland.inc"
include = "scenarios\1648\1648_ENG_England.inc"
include = "scenarios\1648\1648_ETH_Ethiopia.inc"
include = "scenarios\1648\1648_FAT_Calicut.inc"
include = "scenarios\1648\1648_FRA_France.inc"
include = "scenarios\1648\1648_GEN_Genoa.inc"
include = "scenarios\1648\1648_GEO_Georgia.inc"
include = "scenarios\1648\1648_GHA_Ghara.inc"
include = "scenarios\1648\1648_HAA_Al-Haasa.inc"
include = "scenarios\1648\1648_HAB_Austria.inc"
include = "scenarios\1648\1648_HAD_Hadramut.inc"
include = "scenarios\1648\1648_HAN_Hanover.inc"
include = "scenarios\1648\1648_HAS_Hausa.inc"
include = "scenarios\1648\1648_HEL_Switzerland.inc"
include = "scenarios\1648\1648_HES_Hesse.inc"
include = "scenarios\1648\1648_HOL_Netherlands.inc"
include = "scenarios\1648\1648_HYD_Golconda.inc"
include = "scenarios\1648\1648_IST_Ikkeri.inc"
include = "scenarios\1648\1648_KHI_Khiva.inc"
include = "scenarios\1648\1648_KIE_Kilwa.inc"
include = "scenarios\1648\1648_KNI_Order_St_John.inc"
include = "scenarios\1648\1648_KOL_Cologne.inc"
include = "scenarios\1648\1648_KON_Kongo.inc"
include = "scenarios\1648\1648_KOR_Korea.inc"
include = "scenarios\1648\1648_KUR_Courland.inc"
include = "scenarios\1648\1648_KUT_Kutei.inc"
include = "scenarios\1648\1648_KZK_Kazakhs.inc"
include = "scenarios\1648\1648_LKA_Lanka.inc"
include = "scenarios\1648\1648_LOR_Lorraine.inc"
include = "scenarios\1648\1648_LUW_Luwu.inc"
include = "scenarios\1648\1648_MAL_Mali.inc"
include = "scenarios\1648\1648_MAI_Mainz.inc"
include = "scenarios\1648\1648_MAN_Mantua.inc"
include = "scenarios\1648\1648_MEC_Mecklenburg.inc"
include = "scenarios\1648\1648_MLC_Johor.inc"
include = "scenarios\1648\1648_MKS_Makassar.inc"
include = "scenarios\1648\1648_MOG_Mughal_Empire.inc"
include = "scenarios\1648\1648_MOL_Moldavia.inc"
include = "scenarios\1648\1648_MOR_Morocco.inc"
include = "scenarios\1648\1648_MRA_Mahra.inc"
include = "scenarios\1648\1648_MTR_Mataram.inc"
include = "scenarios\1648\1648_MUN_Berg.inc"
include = "scenarios\1648\1648_MYA_Burma.inc"
include = "scenarios\1648\1648_MYS_Mysore.inc"
include = "scenarios\1648\1648_NIP_Japan.inc"
include = "scenarios\1648\1648_OLD_Oldenburg.inc"
include = "scenarios\1648\1648_OMA_Oman.inc"
include = "scenarios\1648\1648_OYO_Oyo.inc"
include = "scenarios\1648\1648_PAL_Palembang.inc"
include = "scenarios\1648\1648_PAM_Modena.inc"
include = "scenarios\1648\1648_PAP_Papal_States.inc"
include = "scenarios\1648\1648_PAR_Parma.inc"
include = "scenarios\1648\1648_PER_Safavids.inc"
include = "scenarios\1648\1648_PFA_Palatinate.inc"
include = "scenarios\1648\1648_POL_Poland.inc"
include = "scenarios\1648\1648_POR_Portugal.inc"
include = "scenarios\1648\1648_PRU_Prussia.inc"
include = "scenarios\1648\1648_RUS_Russia.inc"
include = "scenarios\1648\1648_SAC_Saxony.inc"
include = "scenarios\1648\1648_SAV_Savoy.inc"
include = "scenarios\1648\1648_SCO_Scotland.inc"
include = "scenarios\1648\1648_SHL_Holstein.inc"
include = "scenarios\1648\1648_SIE_Transylvania.inc"
include = "scenarios\1648\1648_SMI_Southern_Ming.inc"
include = "scenarios\1648\1648_SON_Songhai.inc"
include = "scenarios\1648\1648_SPA_Spain.inc"
include = "scenarios\1648\1648_STR_Strasburg.inc"
include = "scenarios\1648\1648_SUD_Nubia.inc"
include = "scenarios\1648\1648_SUL_Sulu.inc"
include = "scenarios\1648\1648_SWA_Bima.inc"
include = "scenarios\1648\1648_SWE_Sweden.inc"
include = "scenarios\1648\1648_TAN_Travancore.inc"
include = "scenarios\1648\1648_TAU_Mu_Bang.inc"
include = "scenarios\1648\1648_TER_Ternate.inc"
include = "scenarios\1648\1648_TIB_Tibet.inc"
include = "scenarios\1648\1648_TOS_Tuscany.inc"
include = "scenarios\1648\1648_TUR_Ottoman_Empire.inc"
include = "scenarios\1648\1648_VEN_Venice.inc"
include = "scenarios\1648\1648_WAL_Wallachia.inc"
include = "scenarios\1648\1648_WUR_Wirtemberg.inc"
include = "scenarios\1648\1648_YEM_Yemen.inc"
include = "scenarios\1648\1648_ZAN_Zanzibar.inc"
include = "scenarios\1648\1648_ZIM_Zimbabwe.inc"

#-----------------------------------------------------------------------------------------------

country = {
	tag = REB
	badboy = 0
	colonialattempts = 0
	colonialnation = no
	major = no
	war = { year = 0 month = january day = 0 }
	lastpeace = { year = 1648 month = january day = 0 }
	cancelledloans = 0
	extendedloans = 0
	treasury = 0.052360
	inflation = 0.002000
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = {
		231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
		252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
		273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293
		294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314
		315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335
		336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356
		357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
		378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398
		399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419
		420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440
		441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 457 458 459 460 461 462
		463 464 465 466 467 468 469 474 475 476 477 478 479 480 481 482 483 484 485 486 490
		491 492 493 494 732 733 734 735 736 737 738 739 740 741 742 744 745 746 806 819 820
		821 836 837 838 839 840 841 868 869 870 871 872 873 874 875 876 877 878 879 880 881
		882 919 920 921 922 923 924 925 926 927 928 929 930 931 932 933 934 935 936 937 938
		939 979 980 981 982 983 984 985 986 987 988 989 990 991 992 993 994 995 996 997 998
		999 1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015
		1016 1017 1057 1058 1331 1361 1362 1466 1469 1470
	}
	ownedprovinces = { }
	controlledprovinces = { }
	nationalprovinces = { }
	monarchtable = { }
	leadertable = { }
	landunit = {
		id = { type = 9423 id = 1053 }
		location = 393 #Napoli
		infantry = 20000
		cavalry = 0
		artillery = 20
	}
	landunit = {
		id = { type = 9423 id = 1085 }
		location = 429 #Catalonia
		infantry = 16000
		cavalry = 6000
		artillery = 20
	}
	landunit = {
		id = { type = 9423 id = 1088 }
		location = 430 #Aragon
		infantry = 12000
		cavalry = 0
		artillery = 20
	}
	technology = {
		land = { date = { year = 0 month = january day = 0 } level = 1 value = 96 }
		naval = { date = { year = 0 month = january day = 0 } level = 0 value = 84 }
		stability = { date = { year = 0 month = january day = 0 } level = 3 value = 0 }
		trade = { date = { year = 0 month = january day = 0 } level = 0 value = 84 }
		infra = { date = { year = 0 month = january day = 0 } level = 0 value = 84 }
		group = exotic
	}
	colonists = 0.000000
	diplomats = 2.000000
	merchants = 1.000000
}

#-----------------------------------------------------------------------------------------------
#Sieges

#Napoli
combat = {
	id = { type = 4712 id = 60178 }
	type = siege
	province = 393
	date = { day = 0 month = january year = 1648 }
	morale = { 4.415 4.415 }
	attackers = { { type = 9423 id = 1053 }	}
	fortress = { inf = 3000 cav = 0 art = 10 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Catalonia
combat = {
	id = { type = 4712 id = 60175 }
	type = siege
	province = 429
	date = { day = 0 month = january year = 1648 }
	morale = { 4.415 4.415 }
	attackers = { { type = 9423 id = 1085 } }
	fortress = { inf = 10 cav = 0 art = 0 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Aragon
combat = {
	id = { type = 4712 id = 60174 }
	type = siege
	province = 430
	date = { day = 0 month = january year = 1648 }
	morale = { 4.415 4.415 }
	attackers = { { type = 9423 id = 1088 } }
	fortress = { inf = 8000 cav = 0 art = 20 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Crete
combat = {
	id = { type = 4712 id = 49286 }
	type = siege
	province = 480
	date = { day = 0 month = january year = 1648 }
	morale = { 4.668 4.543 }
	attackers = { { type = 9423 id = 1111 } }
	fortress = { inf = 8000 cav = 0 art = 20 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Colombo
combat = {
	id = { type = 4712 id = 3986 }
	type = siege
	province = 576
	date = { day = 0 month = january year = 1648 }
	morale = { 5.055 4.313 }
	attackers = { { type = 9423 id = 1010 } }
	fortress = { inf = 5000 cav = 0 art = 10 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}

#-----------------------------------------------------------------------------------------------
