#AGCEEP - 1648 Scenario

#-----------------------------------------------------------------------------------------------
#Provinces: culture and religion changes between 1520 and 1648

#Uzbek Settlement
province = { id = 1532 culture = "uzbehk" } #Bukhara

#The Purge of the Morisques
province = { id = 444 religion = catholic culture = "iberian" } #Granada
province = { id = 445 religion = catholic culture = "iberian" } #Gibraltar
#Spanish Colonies
province = { id = 38 religion = catholic culture = "iberian" } #Mosquitos
province = { id = 37 religion = catholic culture = "iberian" } #Nicaragua
province = { id = 36 religion = catholic culture = "iberian" } #Honduras
province = { id = 35 religion = catholic culture = "iberian" } #Yucatan
province = { id = 34 religion = catholic culture = "iberian" } #Campeche
province = { id = 33 religion = catholic culture = "iberian" } #Guatemala
province = { id = 32 religion = catholic culture = "iberian" } #Tehuacan
province = { id = 31 religion = catholic culture = "iberian" } #Tehuantepec
province = { id = 30 religion = catholic culture = "iberian" } #Atlixco
province = { id = 29 religion = catholic culture = "iberian" } #Tlaxcala
province = { id = 28 religion = catholic culture = "iberian" } #Tampico
province = { id = 27 religion = catholic culture = "iberian" } #Zacatecas
province = { id = 26 religion = catholic culture = "iberian" } #Michoagan
province = { id = 25 religion = catholic culture = "iberian" } #Saltillo
province = { id = 24 religion = catholic culture = "iberian" } #Jalisco
province = { id = 48 religion = catholic culture = "iberian" } #Talahassee
province = { id = 49 religion = catholic culture = "iberian" } #Seminole
province = { id = 50 religion = catholic culture = "iberian" } #Everglades
province = { id = 158 religion = catholic culture = "iberian" } #Cartagena
province = { id = 157 religion = catholic culture = "iberian" } #Maracaibo
province = { id = 156 religion = catholic culture = "iberian" } #Tocuvo
province = { id = 154 religion = catholic culture = "iberian" } #Yaraguay
province = { id = 160 religion = catholic culture = "iberian" } #Bogota
province = { id = 161 religion = catholic culture = "iberian" } #Cupica
province = { id = 162 religion = catholic culture = "iberian" } #Cali
province = { id = 163 religion = catholic culture = "iberian" } #Azuay
province = { id = 164 religion = catholic culture = "iberian" } #Guayaquil
province = { id = 165 religion = catholic culture = "iberian" } #Cajamarca
province = { id = 166 religion = catholic culture = "iberian" } #Huanaco
province = { id = 167 religion = catholic culture = "iberian" } #Ayacucho
province = { id = 168 religion = catholic culture = "iberian" } #Lima
province = { id = 169 religion = catholic culture = "iberian" } #Cuzco
province = { id = 170 religion = catholic culture = "iberian" } #Arequipa
province = { id = 171 religion = catholic culture = "iberian" } #Moquega
province = { id = 172 religion = catholic culture = "iberian" } #Arica
province = { id = 173 religion = catholic culture = "iberian" } #Atacama
province = { id = 174 religion = catholic culture = "iberian" } #Coquimbo
province = { id = 175 religion = catholic culture = "iberian" } #Valparaiso
province = { id = 176 religion = catholic culture = "iberian" } #Talca
province = { id = 192 religion = catholic culture = "iberian" } #Taqari
province = { id = 193 religion = catholic culture = "iberian" } #Titicaca
province = { id = 194 religion = catholic culture = "iberian" } #Potosi
province = { id = 215 religion = catholic culture = "iberian" } #Uruguay
province = { id = 216 religion = catholic culture = "iberian" } #Artigas
province = { id = 217 religion = catholic culture = "iberian" } #Parana
province = { id = 218 religion = catholic culture = "iberian" } #Neembucu
province = { id = 219 religion = catholic culture = "iberian" } #Tucuman
province = { id = 220 religion = catholic culture = "iberian" } #Jujuy
province = { id = 221 religion = catholic culture = "iberian" } #Corrientes
province = { id = 223 religion = catholic culture = "iberian" } #Aires
province = { id = 224 religion = catholic culture = "iberian" } #Copetonas
province = { id = 225 religion = catholic culture = "iberian" } #San Matias
province = { id = 226 religion = catholic culture = "iberian" } #Chubut
province = { id = 227 religion = catholic culture = "iberian" } #Santa Cruz
province = { id = 822 religion = catholic culture = "iberian" } #Costa Rica
province = { id = 690 religion = catholic culture = "iberian" } #Luzon
province = { id = 691 religion = catholic culture = "iberian" } #Mindoro
province = { id = 692 religion = catholic culture = "iberian" } #Samar
province = { id = 1482 religion = catholic culture = "iberian" } #Montana
province = { id = 1483 religion = catholic culture = "iberian" } #Atalaya
province = { id = 1484 religion = catholic culture = "iberian" } #Manu

#Confucianism in Japan
province = { id = 683 religion = confucianism } #Ezochi
province = { id = 684 religion = confucianism } #Tohoku
province = { id = 685 religion = confucianism } #Kanto
province = { id = 686 religion = confucianism } #Kansai
province = { id = 687 religion = confucianism } #Shikoku
province = { id = 688 religion = confucianism } #Kyushu

#Dutch Influence in the Colonies
province = { id = 87 religion = reformed culture = "dutch" } #Manhattan
province = { id = 88 religion = reformed culture = "dutch" } #Catskill
province = { id = 153 religion = reformed culture = "dutch" } #Curacao
province = { id = 179 religion = reformed culture = "dutch" } #Cuyuni
province = { id = 181 religion = reformed culture = "dutch" } #Surinam
province = { id = 702 religion = reformed culture = "dutch" } #Jakarta
province = { id = 706 religion = reformed culture = "dutch" } #Manado
province = { id = 714 religion = reformed culture = "dutch" } #Buru
province = { id = 715 religion = reformed culture = "dutch" } #Ceram
province = { id = 794 religion = reformed culture = "dutch" } #Palanas
province = { id = 795 religion = reformed culture = "dutch" } #Leone
province = { id = 800 religion = reformed culture = "dutch" } #Senegal
province = { id = 802 religion = reformed culture = "dutch" } #Nouakchott
province = { id = 824 religion = reformed culture = "dutch" } #St. Helena
#Special
province = { id = 689 religion = confucianism culture = "han" } #Taiwan

#Portuguese colonial influence
province = { id = 549 religion = catholic } #Goa
province = { id = 576 religion = catholic } #Colombo
province = { id = 577 religion = catholic } #Jaffna
province = { id = 183 religion = catholic culture = "mississippian" } #Amapa
province = { id = 198 religion = catholic culture = "mississippian" } #Marajo
province = { id = 199 religion = catholic culture = "mississippian" } #Para
province = { id = 200 religion = catholic culture = "mississippian" } #Tiracambu
province = { id = 202 religion = catholic culture = "mississippian" } #Parnaiba
province = { id = 203 religion = catholic culture = "mississippian" } #Recife
province = { id = 205 religion = catholic culture = "mississippian" } #Pernambuc
province = { id = 209 religion = catholic culture = "mississippian" } #Salvador
province = { id = 210 religion = catholic culture = "mississippian" } #Itaimas
province = { id = 211 religion = catholic culture = "mississippian" } #Niteroi
province = { id = 711 religion = catholic culture = "mississippian" } #Flores
province = { id = 783 religion = catholic culture = "mississippian" } #Lobito
province = { id = 784 religion = catholic culture = "mississippian" } #Luanda

#Russia
province = { id = 269 culture = "russian" } #Arkhangelsk
province = { id = 451 religion = orthodox culture = "russian" } #Bogutjar
province = { id = 452 religion = orthodox culture = "russian" } #Saratow
province = { id = 453 religion = orthodox culture = "russian" } #Ufa
province = { id = 454 religion = orthodox culture = "russian" } #Samara
province = { id = 458 religion = orthodox culture = "russian" } #Volgograd
#Russian Influence
province = { id = 1573 religion = orthodox culture = "russian" } #Tobolsk
province = { id = 1575 religion = orthodox culture = "russian" } #Sergino
province = { id = 616 religion = orthodox culture = "russian" } #Okhotsk
province = { id = 1467 religion = orthodox culture = "russian" } #Nagorje
province = { id = 1468 religion = orthodox culture = "russian" } #Khretset
province = { id = 632 religion = orthodox culture = "russian" } #Nerchiinsk
province = { id = 589 religion = orthodox culture = "russian" } #Tomsk
province = { id = 600 religion = orthodox culture = "russian" } #Irkutsk
province = { id = 603 religion = orthodox culture = "russian" } #Ulan Ude
province = { id = 591 religion = orthodox culture = "russian" } #Krasnoyarsk
province = { id = 1584 religion = orthodox culture = "russian" } #Saleharo
province = { id = 580 religion = orthodox culture = "russian" } #Omsk
province = { id = 581 religion = orthodox culture = "russian" } #Tchany
province = { id = 582 religion = orthodox culture = "russian" } #Semipalatinsk
province = { id = 584 religion = orthodox culture = "russian" } #Novosibirsk
province = { id = 1571 religion = orthodox culture = "russian" } #Jalutorovsk
province = { id = 517 religion = orthodox culture = "russian" } #Turgai
province = { id = 579 religion = orthodox culture = "russian" } #Karaganda
province = { id = 1570 religion = orthodox culture = "russian" } #Sadrinsk

#France
province = { id = 425 culture = "french" } #Béarn
#French Colonies
province = { id = 106 religion = catholic culture = "french" } #Hochelaga
province = { id = 109 religion = catholic culture = "french" } #Shawinigan
province = { id = 110 religion = catholic culture = "french" } #Stadacone
province = { id = 111 religion = catholic culture = "french" } #Bas St-Laurent
province = { id = 114 religion = catholic culture = "french" } #Gaspésie
province = { id = 117 religion = catholic culture = "french" } #Isle Royale
province = { id = 146 religion = catholic culture = "french" } #St. Martin
province = { id = 149 religion = catholic culture = "french" } #Guadeloupe
province = { id = 150 religion = catholic culture = "french" } #Martinique
province = { id = 809 religion = catholic culture = "french" } #Bourbon

#Europe
province = { id = 232 religion = reformed } #Ulster
province = { id = 263 culture = "scandinavian" } #Österbotten
province = { id = 298 religion = catholic } #Galizien
province = { id = 337 culture = "dutch" } #Friesen
province = { id = 467 religion = buddhism } #Kalmuk
province = { id = 1466 religion = protestant } #Iceland
#The Edict of Restitution
province = { id = 330 culture = "german" religion = catholic } #Sudeten
province = { id = 314 religion = catholic } #Silesia
province = { id = 328 religion = catholic } #Bohemia
province = { id = 329 religion = catholic } #Erz

#Welsh Act of Union
province = { id = 243 culture = "anglosaxon" } #Wales
#English Colonies
province = { id = 64 religion = protestant culture = "anglosaxon" } #Roanoke
province = { id = 68 religion = protestant culture = "anglosaxon" } #Chesapeake
province = { id = 102 religion = reformed culture = "anglosaxon" } #Connecticut
province = { id = 103 religion = reformed culture = "anglosaxon" } #Massachusetts
province = { id = 104 religion = reformed culture = "anglosaxon" } #Penobscot
province = { id = 1568 religion = protestant culture = "anglosaxon" } #Bermuda
province = { id = 1569 religion = protestant culture = "anglosaxon" } #Bahamas
province = { id = 147 religion = protestant culture = "anglosaxon" } #Antigua
province = { id = 152 religion = protestant culture = "anglosaxon" } #Barbados

#Ukraine and ukrainian culture provinces
province = { id = 295 culture = "ukrainian" } #Ukraine
province = { id = 460 culture = "ukrainian" } #Donetsk
province = { id = 461 culture = "ukrainian" } #Poltava
province = { id = 462 religion = orthodox culture = "ukrainian" } #Krementjug

#The Islamization of Indonesia
province = { id = 694 religion = sunni } #Palawan
province = { id = 697 religion = sunni } #Sarawak
province = { id = 699 religion = sunni } #Selatan
province = { id = 700 religion = sunni } #Kalimantan
province = { id = 701 religion = sunni } #Sunda
province = { id = 709 religion = sunni } #Salabanka
province = { id = 710 religion = sunni } #Sumbawa

#Oromo invasions
province = { id = 1589 religion = sunni } #Kefa
province = { id = 758 culture = "ethiopian" } #Ogaden

#Others
province = { id = 578 religion = sunni } #Ichim
province = { id = 691 religion = catholic } #Mindoro
province = { id = 86 religion = protestant culture = "scandinavian" } #Delaware
province = { id = 145 religion = protestant culture = "scandinavian" } #St. Thomas
province = { id = 664 religion = confucianism } #Da Nang
province = { id = 665 religion = confucianism } #Da Lat


#Natives
province = { id = 216 natives = 0 } #Artigas

#-----------------------------------------------------------------------------------------------
