#AGCEEP - 1648 Scenario

#-----------------------------------------------------------------------------------------------
#Countries

include = "scenarios\1648\1648_ADA_Adal.inc"
include = "scenarios\1648\1648_ANG_Angoche.inc"
include = "scenarios\1648\1648_ANN_Annam.inc"
include = "scenarios\1648\1648_ARK_Arakan.inc"
include = "scenarios\1648\1648_ASH_Ashanti.inc"
include = "scenarios\1648\1648_ATJ_Atjeh.inc"
include = "scenarios\1648\1648_AYU_Ayutthaya.inc"
include = "scenarios\1648\1648_BAL_Baluchistan.inc"
include = "scenarios\1648\1648_BAY_Bavaria.inc"
include = "scenarios\1648\1648_BEI_Brunei.inc"
include = "scenarios\1648\1648_BEN_Benin.inc"
include = "scenarios\1648\1648_BGL_Bengal.inc"
include = "scenarios\1648\1648_BIM_Bima.inc"
include = "scenarios\1648\1648_BJR_Banjar.inc"
include = "scenarios\1648\1648_BLI_Bali.inc"
include = "scenarios\1648\1648_BRA_Brandenburg.inc"
include = "scenarios\1648\1648_BRG_Berg.inc"
include = "scenarios\1648\1648_BRM_Burma.inc"
include = "scenarios\1648\1648_BTN_Banten.inc"
include = "scenarios\1648\1648_BUK_Bukhara.inc"
include = "scenarios\1648\1648_BUT_Butung.inc"
include = "scenarios\1648\1648_CAM_Cambodia.inc"
include = "scenarios\1648\1648_CHG_Chagatai.inc"
include = "scenarios\1648\1648_CHI_China.inc"
include = "scenarios\1648\1648_CLC_Calicut.inc"
include = "scenarios\1648\1648_CRI_Crimea.inc"
include = "scenarios\1648\1648_DAH_Dahomey.inc"
include = "scenarios\1648\1648_DAI_Dai_Viet.inc"
include = "scenarios\1648\1648_DAN_Denmark.inc"
include = "scenarios\1648\1648_DAS_Da_Shun.inc"
include = "scenarios\1648\1648_DAX_Da_Xi.inc"
include = "scenarios\1648\1648_EIR_Ireland.inc"
include = "scenarios\1648\1648_ENG_England.inc"
include = "scenarios\1648\1648_ETH_Ethiopia.inc"
include = "scenarios\1648\1648_FRA_France.inc"
include = "scenarios\1648\1648_GEN_Genoa.inc"
include = "scenarios\1648\1648_GEO_Georgia.inc"
include = "scenarios\1648\1648_GHR_Ghara.inc"
include = "scenarios\1648\1648_GOL_Golconda.inc"
include = "scenarios\1648\1648_HAA_Al-Haasa.inc"
include = "scenarios\1648\1648_HAB_Austria.inc"
include = "scenarios\1648\1648_HAD_Hadramut.inc"
include = "scenarios\1648\1648_HAN_Hanover.inc"
include = "scenarios\1648\1648_HAS_Hausa.inc"
include = "scenarios\1648\1648_HEL_Switzerland.inc"
include = "scenarios\1648\1648_HES_Hesse.inc"
include = "scenarios\1648\1648_HOL_Netherlands.inc"
include = "scenarios\1648\1648_IKK_Ikkeri.inc"
include = "scenarios\1648\1648_KHI_Khiva.inc"
include = "scenarios\1648\1648_KIL_Kilwa.inc"
include = "scenarios\1648\1648_KNI_Order_St_John.inc"
include = "scenarios\1648\1648_KOL_Cologne.inc"
include = "scenarios\1648\1648_KON_Kongo.inc"
include = "scenarios\1648\1648_KOR_Korea.inc"
include = "scenarios\1648\1648_KUR_Courland.inc"
include = "scenarios\1648\1648_KUT_Kutei.inc"
include = "scenarios\1648\1648_KZK_Kazakhs.inc"
include = "scenarios\1648\1648_LAX_Lan_Xang.inc"
include = "scenarios\1648\1648_LNK_Lanka.inc"
include = "scenarios\1648\1648_LOR_Lorraine.inc"
include = "scenarios\1648\1648_LUW_Luwu.inc"
include = "scenarios\1648\1648_MAD_Madurai.inc"
include = "scenarios\1648\1648_MAI_Mainz.inc"
include = "scenarios\1648\1648_MAL_Mali.inc"
include = "scenarios\1648\1648_MAN_Mantua.inc"
include = "scenarios\1648\1648_MEC_Mecklenburg.inc"
include = "scenarios\1648\1648_MGU_Mogadishu.inc"
include = "scenarios\1648\1648_MKS_Makassar.inc"
include = "scenarios\1648\1648_MLC_Johor.inc"
include = "scenarios\1648\1648_MLI_Malindi.inc"
include = "scenarios\1648\1648_MND_Magindanao.inc"
include = "scenarios\1648\1648_MOD_Modena.inc"
include = "scenarios\1648\1648_MOG_Mughal_Empire.inc"
include = "scenarios\1648\1648_MOL_Moldavia.inc"
include = "scenarios\1648\1648_MOR_Morocco.inc"
include = "scenarios\1648\1648_MRA_Mahra.inc"
include = "scenarios\1648\1648_MTR_Mataram.inc"
include = "scenarios\1648\1648_MUB_Mu_Bang.inc"
include = "scenarios\1648\1648_MYS_Mysore.inc"
include = "scenarios\1648\1648_NIP_Japan.inc"
include = "scenarios\1648\1648_NUB_Nubia.inc"
include = "scenarios\1648\1648_OLD_Oldenburg.inc"
include = "scenarios\1648\1648_OMA_Oman.inc"
include = "scenarios\1648\1648_OYO_Oyo.inc"
include = "scenarios\1648\1648_PAL_Palembang.inc"
include = "scenarios\1648\1648_PAP_Papal_States.inc"
include = "scenarios\1648\1648_PAR_Parma.inc"
include = "scenarios\1648\1648_PER_Safavids.inc"
include = "scenarios\1648\1648_PFA_Palatinate.inc"
include = "scenarios\1648\1648_POL_Poland.inc"
include = "scenarios\1648\1648_POR_Portugal.inc"
include = "scenarios\1648\1648_PRU_Prussia.inc"
include = "scenarios\1648\1648_RUS_Russia.inc"
include = "scenarios\1648\1648_SAC_Saxony.inc"
include = "scenarios\1648\1648_SAV_Savoy.inc"
include = "scenarios\1648\1648_SCO_Scotland.inc"
include = "scenarios\1648\1648_SHL_Holstein.inc"
include = "scenarios\1648\1648_SMI_Southern_Ming.inc"
include = "scenarios\1648\1648_SON_Songhai.inc"
include = "scenarios\1648\1648_SPA_Spain.inc"
include = "scenarios\1648\1648_STR_Strasburg.inc"
include = "scenarios\1648\1648_SUL_Sulu.inc"
include = "scenarios\1648\1648_SWE_Sweden.inc"
include = "scenarios\1648\1648_TER_Ternate.inc"
include = "scenarios\1648\1648_TIB_Tibet.inc"
include = "scenarios\1648\1648_TOS_Tuscany.inc"
include = "scenarios\1648\1648_TRA_Transylvania.inc"
include = "scenarios\1648\1648_TRV_Travancore.inc"
include = "scenarios\1648\1648_TUR_Ottoman_Empire.inc"
include = "scenarios\1648\1648_VEN_Venice.inc"
include = "scenarios\1648\1648_WAL_Wallachia.inc"
include = "scenarios\1648\1648_WUR_Wirtemberg.inc"
include = "scenarios\1648\1648_YEM_Yemen.inc"
include = "scenarios\1648\1648_ZAN_Zanzibar.inc"
include = "scenarios\1648\1648_ZIM_Zimbabwe.inc"

#-----------------------------------------------------------------------------------------------
#Rebel factions

country = {
	tag = REB
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	landunit = {
		id = { type = 9423 id = 1053 }
		location = 393 #Napoli
		infantry = 20000
		cavalry = 0
		artillery = 20
	}
	landunit = {
		id = { type = 9423 id = 1085 }
		location = 429 #Catalonia
		infantry = 16000
		cavalry = 6000
		artillery = 20
	}
	landunit = {
		id = { type = 9423 id = 1088 }
		location = 430 #Aragon
		infantry = 12000
		cavalry = 0
		artillery = 20
	}
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R01
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R02
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R03
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R04
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R05
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R06
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = NDR
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = USR
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------
#Sieges

#Napoli
combat = {
	id = { type = 4712 id = 60178 }
	type = siege
	province = 393
	date = { day = 0 month = january year = 1648 }
	morale = { 4.415 4.415 }
	attackers = { { type = 9423 id = 1053 }	}
	fortress = { inf = 3000 cav = 0 art = 10 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Catalonia
combat = {
	id = { type = 4712 id = 60175 }
	type = siege
	province = 429
	date = { day = 0 month = january year = 1648 }
	morale = { 4.415 4.415 }
	attackers = { { type = 9423 id = 1085 } }
	fortress = { inf = 10 cav = 0 art = 0 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Aragon
combat = {
	id = { type = 4712 id = 60174 }
	type = siege
	province = 430
	date = { day = 0 month = january year = 1648 }
	morale = { 4.415 4.415 }
	attackers = { { type = 9423 id = 1088 } }
	fortress = { inf = 8000 cav = 0 art = 20 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Crete
combat = {
	id = { type = 4712 id = 49286 }
	type = siege
	province = 480
	date = { day = 0 month = january year = 1648 }
	morale = { 4.668 4.543 }
	attackers = { { type = 9423 id = 1111 } }
	fortress = { inf = 8000 cav = 0 art = 20 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}
#Colombo
combat = {
	id = { type = 4712 id = 3986 }
	type = siege
	province = 576
	date = { day = 0 month = january year = 1648 }
	morale = { 5.055 4.313 }
	attackers = { { type = 9423 id = 1010 } }
	fortress = { inf = 5000 cav = 0 art = 10 }
	siege_p = 0
	siege_d = 0.000
	siege_breaches = 0
}

#-----------------------------------------------------------------------------------------------
