#AGCEEP - 1648 Scenario

#-----------------------------------------------------------------------------------------------
#Provinces: miscellaneous

#English Civil War
province = { id = 233 province_revoltrisk = 5 } #Meath
province = { id = 234 province_revoltrisk = 5 } #Leinster
province = { id = 243 province_revoltrisk = 5 } #Wales
province = { id = 246 province_revoltrisk = 5 } #Bristol
province = { id = 250 province_revoltrisk = 5 } #Cornwall
province = { id = 240 province_revoltrisk = 5 } #Northumberland

#Revolts in Corsica
province = { id = 398 province_revoltrisk = 1 } #Corsica

#Looted provinces
province = { id = 231 date = { day = 0 month = january year = 1649 } looted = yes } #Connaught
province = { id = 234 date = { day = 0 month = january year = 1649 } looted = yes } #Leinster
province = { id = 393 date = { day = 0 month = january year = 1649 } looted = yes } #Napoli
province = { id = 426 date = { day = 0 month = january year = 1649 } looted = yes } #Roussillon
province = { id = 427 date = { day = 0 month = january year = 1649 } looted = yes } #Gerona
province = { id = 429 date = { day = 0 month = january year = 1649 } looted = yes } #Catalonia
province = { id = 430 date = { day = 0 month = january year = 1649 } looted = yes } #Aragon
province = { id = 480 date = { day = 0 month = january year = 1649 } looted = yes } #Crete
province = { id = 576 date = { day = 0 month = january year = 1649 } looted = yes } #Colombo

#-----------------------------------------------------------------------------------------------
