#AGCEEP - 1648 Scenario

#-----------------------------------------------------------------------------------------------
#Provinces : mines changes between 1520 and 1648 - production in 1419 at the end of each line

#America
province = { id = 15 mine = 10 } #Altar (2)
province = { id = 24 mine = 29 } #Jalisco (5)
province = { id = 25 mine = 79 } #Saltillo (5)
province = { id = 26 mine = 17 } #Michoagan (5)
province = { id = 27 mine = 123 } #Zacatecas (5)
province = { id = 160 mine = 28 } #Bogota (0)
province = { id = 162 mine = 36 } #Cali (0)
province = { id = 168 mine = 31 } #Lima (0)
province = { id = 169 mine = 13 } #Cuzco (7)
province = { id = 170 mine = 42 } #Arequipa (0)
province = { id = 175 mine = 1 } #Valparaiso (5)
province = { id = 194 mine = 436 } #Potosi (5)

#Africa
province = { id = 795 mine = 25 } #Leone (5)
province = { id = 1488 mine = 0 } #Bambuk (Walata) (20)
province = { id = 1489 mine = 0 } #Bure (Jenne) (20)

#Asia
province = { id = 686 mine = 124 } #Kansai (10)

#Europe
province = { id = 328 mine = 3 } #Bohemia (25)
province = { id = 330 mine = 39 } #Sudeten (5)
province = { id = 371 mine = 7 } #Tirol (5)

#-----------------------------------------------------------------------------------------------
