#AGCEEP - 1648 Scenario

#-----------------------------------------------------------------------------------------------
#Centers of Trade
#
# There are 30 possible CoT's in a game. There will always be a minimum of 22 CoT's.
# If a scenario has less then new CoT's will be created by the game.
# The color a CoT is displayed on the Trade map is based on what position it is in.
# Each position uses a color defined in colorscales.csv.
# There are only 22 available colors, so colors are reused starting with the 23rd CoT
# and continues in the same order as CoT 1 - 22.

#CoT 1 - Green
#Jakarta
cot = {
	location = 702
	merchant = { TAG = HOL level = 6 }
	merchant = { TAG = MLC level = 3 }
	merchant = { TAG = BTM level = 1 }
	merchant = { TAG = MKS level = 2 }
	merchant = { TAG = ENG level = 2 }
}

#CoT 2 - Red
#Holland
cot = {
	location = 339
	merchant = { TAG = HOL level = 6 }
}

#CoT 3 - LightBlue
#Kyushu
cot = {
	location = 688
	merchant = { TAG = NIP level = 5 }
	merchant = { TAG = HOL level = 5 }
}

#CoT 4 - LightGray
#Danzig
cot = {
	location = 301
	merchant = { TAG = HOL level = 4 }
	merchant = { TAG = POL level = 2 }
}

#CoT 5 - LightBrown
#Firenze
cot = {
	location = 401
	merchant = { TAG = TOS level = 4 }
}

#CoT 6 - DarkYellow
#Zanzibar
cot = {
	location = 765
	merchant = { TAG = HOL level = 2 }
	merchant = { TAG = POR level = 2 }
}

#CoT 7 - Yellow
#Mascate
cot = {
	location = 504
	merchant = { TAG = OMA level = 4 }
	merchant = { TAG = HAD level = 2 }
	merchant = { TAG = HOL level = 2 }
	merchant = { TAG = ENG level = 1 }
}

#CoT 8 - DarkGray
#Pernambuco
cot = {
	location = 205
	merchant = { TAG = POR level = 4 }
}

#CoT 9 - LightYellow
#Veneto
cot = {
	location = 370
	merchant = { TAG = VEN level = 2 }
	merchant = { TAG = HAB level = 2 }
	merchant = { TAG = SAC level = 2 }
	merchant = { TAG = BAY level = 2 }
}

#CoT 10 - Gray
#Muscovy
cot = {
	location = 279
	merchant = { TAG = RUS level = 3 }
	merchant = { TAG = HOL level = 2 }
}

#CoT 11 - DarkGreen
#Tobolsk
cot = {
	location = 1573
	merchant = { TAG = RUS level = 5 }
}

#CoT 12 - Blue
#Surat
cot = {
	location = 547
	merchant = { TAG = MOG level = 3 }
	merchant = { TAG = POR level = 3 }
}

#CoT 13 - LightRed
#Howrah
cot = {
	location = 558
	merchant = { TAG = MOG level = 2 }
}

#CoT 14 - White
#Seville
cot = {
	location = 443
	merchant = { TAG = SPA level = 5 }
	merchant = { TAG = GEN level = 2 }
}

#CoT 15 - DarkBrown
#Cartagena
cot = {
	location = 158
	merchant = { TAG = SPA level = 4 }
	merchant = { TAG = ENG level = 2 }
}

#CoT 16 - Red
#Lyonnais
cot = {
	location = 408
	merchant = { TAG = FRA level = 4 }
}

#CoT 17 - LightGreen
#Anglia
cot = {
	location = 247
	merchant = { TAG = ENG level = 5 }
}

#CoT 18 - LightOrnage
#Thrace
cot = {
	location = 357
	merchant = { TAG = TUR level = 4 }
	merchant = { TAG = CRI level = 3 }
}

#CoT 19 - Brown
#Alexandria
cot = {
	location = 744
	merchant = { TAG = TUR level = 3 }
	merchant = { TAG = VEN level = 3 }
	merchant = { TAG = FRA level = 2 }
}

#CoT 20 - DarkBlue
#Lima
cot = {
	location = 168
	merchant = { TAG = SPA level = 5 }
}

#CoT 21 - DarkRed
#Guangdong
cot = {
	location = 659
	merchant = { TAG = SMI level = 5 }
	merchant = { TAG = POR level = 3 }
}

#CoT 22 - DarkOrange
#Nanjing
cot = {
	location = 653
	merchant = { TAG = CHI level = 4 }
}

# CoT 23 - Green
#Isfahan
cot = {
	location = 533
	merchant = { TAG = PER level = 3 }
	merchant = { TAG = ENG level = 1 }
	merchant = { TAG = HOL level = 1 }
}

#CoT 24 - DarkRed
#Palanas
cot = {
	location = 794
	merchant = { TAG = HOL level = 3 }
}

#-----------------------------------------------------------------------------------------------
