#AGCEEP - The Grand Campaign - 1419

#-----------------------------------------------------------------------------------------------
#Provinces: miscellaneous

province = { id = 671 nationalism = { year = 1440 month = january day = 1 } } #Chin

province = { id = 243
		control = { year = 1413 } #Wales after Glwyndir rebellion
		ownerchange = { year = 1413 }
		nationalism = { year = 1413 }
		}

province = { id = 388 
		control = { year = 1415 month = may day = 7 } #Aargau conquered by Old Swiss Confederacy from Tyrol
		ownerchange = { year = 1415 month = may day = 7 }
		nationalism = { year = 1415 month = may day = 7 }
		}
province = { id = 1612 
		control = { year = 1411 month = november day = 24} #Appenzell entered into Swiss alliance Appenzellerkrieg
		ownerchange = { year = 1411 month = november day = 24 }
		nationalism = { year = 1411 month = november day = 24 }
		}

province = { id = 311 
		control = { year = 1414 month = march day = 20 } #Friedrich of Nürnberg had full control only from 1414 onward
		ownerchange = { year = 1414 month = march day = 20 }
		nationalism = { year = 1414 month = march day = 20 }
		}
province = { id = 312 
		control = { year = 1414 month = march day = 20} 
		ownerchange = { year = 1414 month = march day = 20 }
		nationalism = { year = 1414 month = march day = 20 }
		}

province = { id = 308 
		control = { year = 1408 month = january day = 1 } #Gotland to Denmark
		ownerchange = { year = 1408 month = january day = 1 }
		nationalism = { year = 1408 month = january day = 1 }
		}

province = { id = 662 
		control = { year = 1407 month = may day = 30 } 
		ownerchange = { year = 1407 month = june day = 16 }
		nationalism = { year = 1407 month = june day = 16 } #Ming-Ho War invasion of Annam
		province_revoltrisk = 797 
		} #Hanoi
province = { id = 663 province_revoltrisk = 797 
		control = { year = 1407 month = may day = 30 } 
		ownerchange = { year = 1407 month = june day = 16 }
		nationalism = { year = 1407 month = june day = 16 }
		} #Tanh Noah
province = { id = 1554 
		province_revoltrisk = 797 
		control = { year = 1407 month = may day = 30 } 
		ownerchange = { year = 1407 month = june day = 16 }
		nationalism = { year = 1407 month = june day = 16 }
		} #Lao Cai

#Yongle was an usurper who stole the Dragon Throne from his nephew 
province = { id = 650 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 651 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 652 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 653 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }		
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 654 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 655 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 656 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 657 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 658 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 659 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 660 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 661 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 1553 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 1555 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 1556 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 1558 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 1559 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 1560 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 1561 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 1562 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 1563 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 1564 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 1565 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 1566 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }
province = { id = 1567 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } } 
province = { id = 1608 
		control = { year = 1402 month = july day = 17 } 
		ownerchange = { year = 1402 month = july day = 17 }
		nationalism = { year = 1402 month = july day = 17 } }

#Looted provinces
province = { id = 365 date = { day = 0 month = january year = 1420 } looted = yes } #Dalmatia
province = { id = 368 date = { day = 0 month = january year = 1420 } looted = yes } #Istria
province = { id = 413 date = { day = 0 month = january year = 1420 } looted = yes } #Normandy
province = { id = 413 control = { day = 22 month = september year = 1415 } } #Normandy occupied since 1415 after siege of Harfleur

#-----------------------------------------------------------------------------------------------
