#AGCEEP - The Grand Campaign - 1419

#-----------------------------------------------------------------------------------------------
#Provinces: miscellaneous

province = { id = 671 nationalism = { year = 1440 month = january day = 1 } } #Chin

province = { id = 662 province_revoltrisk = 800 } #Hanoi
province = { id = 663 province_revoltrisk = 800 } #Tanh Noah
province = { id = 1554 province_revoltrisk = 800 } #Lao Cai

#Looted provinces
province = { id = 365 date = { day = 0 month = january year = 1420 } looted = yes } #Dalmatia
province = { id = 368 date = { day = 0 month = january year = 1420 } looted = yes } #Istria
province = { id = 413 date = { day = 0 month = january year = 1420 } looted = yes } #Normandy
province = { id = 413 control = { day = 22 month = september year = 1415 } } #Normandy occupied since 1415 after siege of Harfleur

#-----------------------------------------------------------------------------------------------
