#AGCEEP - 1520 Scenario

#-----------------------------------------------------------------------------------------------
#Provinces : mines changes between 1419 and 1520 - production in 1419 at the end of each line

#Africa
province = { id = 795 mine = 28 } #Leone (5)
province = { id = 1508 mine = 10 } #Sofala (25)
province = { id = 1511 mine = 10 } #Nembire (25)

#Asia
province = { id = 1553 mine = 4 } #Yunnan (46)
province = { id = 1558 mine = 4 } #Lanzhou (46)

#Europe
province = { id = 328 mine = 6 } #Bohemia (25)
province = { id = 330 mine = 10 } #Sudeten (5)
province = { id = 331 mine = 10 } #Sachsen (5)
province = { id = 371 mine = 27 } #Tirol (5)

#-----------------------------------------------------------------------------------------------
