#AGCEEP - 1520 Scenario

#-----------------------------------------------------------------------------------------------
#Provinces: culture and religion changes between 1419 and 1520

#Dutch provinces
province = { id = 338 culture = "dutch" } #Geldre

#Islam spread to Nubia
province = { id = 749 religion = sunni } #Nubia
province = { id = 750 religion = sunni } #Sudan
province = { id = 751 religion = sunni } #Bisharin

#Turkish expansion
province = { id = 356 religion = sunni } #Bulgaria
province = { id = 361 religion = sunni } #Albania
province = { id = 357 religion = sunni culture = "turkish" } #Thrace
province = { id = 358 culture = "turkish" } #Macedonia
province = { id = 362 culture = "albanian" } #Ragusa
province = { id = 364 religion = sunni } #Bosnia
province = { id = 464 religion = sunni culture = "turkish" } #Kaffa
province = { id = 465 religion = sunni culture = "turkish" } #Kerch
province = { id = 477 religion = sunni } #Anatolia
province = { id = 478 religion = sunni culture = "turkish" } #Smyrna
province = { id = 483 religion = sunni } #Adana

#The Conversion of Persia
province = { id = 487 religion = shiite } #Azerbaijan
province = { id = 525 religion = shiite } #Elbruz
province = { id = 526 religion = shiite } #Meched
province = { id = 527 religion = shiite } #Kerman
province = { id = 528 religion = shiite } #Lut
province = { id = 533 religion = shiite } #Isfahan
province = { id = 534 religion = shiite } #Fars
province = { id = 535 religion = shiite } #Hormouz
province = { id = 1529 religion = shiite } #Birjand
province = { id = 1530 religion = shiite } #Khorasan

#Uzbek Settlement
province = { id = 1534 culture = "uzbehk" } #Kyzylkum
province = { id = 1594 culture = "uzbehk" } #Uzbek
province = { id = 522 culture = "uzbehk" } #Khwarizm
province = { id = 1592 culture = "uzbehk" } #Samarkand
province = { id = 1533 culture = "uzbehk" } #Khiva

#Kazakh Settlement
province = { id = 516 culture = "khazak" } #Aralsk
province = { id = 517 culture = "khazak" } #Turgai
province = { id = 518 culture = "khazak" } #Ust Urt
province = { id = 579 culture = "khazak" } #Karaganda
province = { id = 1535 culture = "khazak" } #Karsak
province = { id = 1536 culture = "khazak" } #Nura

#Europe
province = { id = 263 culture = "ugric" } #Österbotten
province = { id = 327 culture = "german" } #Ostmarch
province = { id = 352 culture = "german" } #Odenburg
province = { id = 354 culture = "slavonic" } #Banat

#Africa
province = { id = 785 religion = catholic } #Zaire
province = { id = 786 religion = catholic } #Cabinda
province = { id = 1494 religion = sunni } #Ouagadougou (Bure)
province = { id = 1495 religion = sunni } #Timbuktu
province = { id = 1497 religion = sunni } #Say
province = { id = 1501 religion = sunni } #Kano
province = { id = 1590 religion = sunni } #Bale

#Spanish Colonies
province = { id = 39 religion = catholic culture = "iberian" } #Isthmus
province = { id = 137 religion = catholic culture = "iberian" } #Havana
province = { id = 138 religion = catholic culture = "iberian" } #Moron
province = { id = 139 religion = catholic culture = "iberian" } #Guantanamo
province = { id = 140 religion = catholic culture = "iberian" } #Jamaica
province = { id = 142 religion = catholic culture = "iberian" } #Tortuga
province = { id = 143 religion = catholic culture = "iberian" } #Barahona
province = { id = 144 religion = catholic culture = "iberian" } #Puerto Rico
province = { id = 151 religion = catholic culture = "iberian" } #Tobago & Trinidad

#Portuguese colonial influence
province = { id = 207 religion = catholic culture = "mississippian" } #Diamentina
province = { id = 712 religion = catholic culture = "mississippian" } #Timor
province = { id = 715 religion = catholic culture = "mississippian" } #Ceram
province = { id = 768 religion = catholic culture = "mississippian" } #Mtawa
province = { id = 770 religion = catholic culture = "mississippian" } #Nampuia
province = { id = 795 religion = catholic culture = "mississippian" } #Leone
province = { id = 800 religion = catholic culture = "mississippian" } #Senegal
province = { id = 816 religion = catholic culture = "mississippian" } #Fernando Po
province = { id = 818 religion = catholic culture = "mississippian" } #Cape Verde

#The Islamization of Indonesia
province = { id = 676 religion = sunni culture = "malay" } #Perak
province = { id = 677 religion = sunni } #Malacca
province = { id = 680 religion = sunni } #Riau
province = { id = 698 religion = sunni } #Bandjarmasin
province = { id = 703 religion = sunni } #Bandung
province = { id = 708 religion = sunni } #Makassar
province = { id = 704 religion = sunni } #Surabaja
province = { id = 682 religion = sunni } #Palembang
province = { id = 693 religion = sunni } #Mindanao
province = { id = 706 religion = sunni } #Manado
province = { id = 713 religion = sunni } #Tindore

#Others
province = { id = 1522 religion = hinduism } #Bikaner
province = { id = 689 culture = "indian" tolerance = 0 } #Taiwan

#-----------------------------------------------------------------------------------------------
