#AGCEEP - 1520 Scenario

#-----------------------------------------------------------------------------------------------
#Provinces: miscellaneous

#Rajput cultural minorities uprising
province = { id = 543 province_revoltrisk = 1 } #Delhi
province = { id = 546 province_revoltrisk = 1 } #Malwa
province = { id = 1521 province_revoltrisk = 1 } #Panjab

#Japan
province = { id = 684 province_revoltrisk = 2 } #Tohoku
province = { id = 685 province_revoltrisk = 10 } #Kanto
province = { id = 686 province_revoltrisk = 10 } #Kansai
province = { id = 687 province_revoltrisk = 10 } #Shikoku
province = { id = 688 province_revoltrisk = 8 } #Kyushu

#-----------------------------------------------------------------------------------------------
