#AGCEEP - 1520 Scenario

#-----------------------------------------------------------------------------------------------
#Countries

include = "scenarios\1520\1520_ABK_Abkhazia.inc"
include = "scenarios\1520\1520_ADA_Adal.inc"
include = "scenarios\1520\1520_ADE_Aden.inc"
include = "scenarios\1520\1520_AHM_Ahmadnagar.inc"
include = "scenarios\1520\1520_ALD_Algiers.inc"
include = "scenarios\1520\1520_ANG_Angoche.inc"
include = "scenarios\1520\1520_ARK_Arakan.inc"
include = "scenarios\1520\1520_ASH_Ashanti.inc"
include = "scenarios\1520\1520_AST_Astrakhan.inc"
include = "scenarios\1520\1520_ATJ_Atjeh.inc"
include = "scenarios\1520\1520_AYU_Ayutthaya.inc"
include = "scenarios\1520\1520_AZT_Aztec_Empire.inc"
include = "scenarios\1520\1520_BAL_Baluchistan.inc"
include = "scenarios\1520\1520_BAY_Bavaria.inc"
include = "scenarios\1520\1520_BEI_Brunei.inc"
include = "scenarios\1520\1520_BEN_Benin.inc"
include = "scenarios\1520\1520_BGL_Bengal.inc"
include = "scenarios\1520\1520_BIJ_Bijapur.inc"
include = "scenarios\1520\1520_BIM_Bima.inc"
include = "scenarios\1520\1520_BJR_Banjar.inc"
include = "scenarios\1520\1520_BLI_Bali.inc"
include = "scenarios\1520\1520_BOH_Bohemia.inc"
include = "scenarios\1520\1520_BRA_Brandenburg.inc"
include = "scenarios\1520\1520_BRE_Bremen.inc"
include = "scenarios\1520\1520_BRI_Brittany.inc"
include = "scenarios\1520\1520_BRM_Burma.inc"
include = "scenarios\1520\1520_BTN_Banten.inc"
include = "scenarios\1520\1520_BUT_Butung.inc"
include = "scenarios\1520\1520_CAM_Cambodia.inc"
include = "scenarios\1520\1520_CHG_Chagatai.inc"
include = "scenarios\1520\1520_CHI_China.inc"
include = "scenarios\1520\1520_CLC_Calicut.inc"
include = "scenarios\1520\1520_CRI_Crimea.inc"
include = "scenarios\1520\1520_DAH_Dahomey.inc"
include = "scenarios\1520\1520_DAI_Dai_Viet.inc"
include = "scenarios\1520\1520_DAN_Denmark.inc"
include = "scenarios\1520\1520_DLH_Delhi.inc"
include = "scenarios\1520\1520_ENG_England.inc"
include = "scenarios\1520\1520_ETH_Ethiopia.inc"
include = "scenarios\1520\1520_FOI_Foix.inc"
include = "scenarios\1520\1520_FRA_France.inc"
include = "scenarios\1520\1520_FRI_Friesland.inc"
include = "scenarios\1520\1520_GEL_Guelders.inc"
include = "scenarios\1520\1520_GEN_Genoa.inc"
include = "scenarios\1520\1520_GHR_Ghara.inc"
include = "scenarios\1520\1520_GOL_Golconda.inc"
include = "scenarios\1520\1520_GON_Gondwana.inc"
include = "scenarios\1520\1520_GUJ_Gujarat.inc"
include = "scenarios\1520\1520_HAA_Al-Haasa.inc"
include = "scenarios\1520\1520_HAB_Austria.inc"
include = "scenarios\1520\1520_HAD_Hadramut.inc"
include = "scenarios\1520\1520_HAN_Hanover.inc"
include = "scenarios\1520\1520_HAS_Hausa.inc"
include = "scenarios\1520\1520_HEL_Switzerland.inc"
include = "scenarios\1520\1520_HES_Hesse.inc"
include = "scenarios\1520\1520_HUN_Hungary.inc"
include = "scenarios\1520\1520_HYA_Haihaya.inc"
include = "scenarios\1520\1520_IMR_Imereti.inc"
include = "scenarios\1520\1520_INC_Inca_Empire.inc"
include = "scenarios\1520\1520_KAK_Kakheti.inc"
include = "scenarios\1520\1520_KAZ_Kazan.inc"
include = "scenarios\1520\1520_KHI_Khiva.inc"
include = "scenarios\1520\1520_KIL_Kilwa.inc"
include = "scenarios\1520\1520_KLE_Cleves.inc"
include = "scenarios\1520\1520_KNI_Order_St_John.inc"
include = "scenarios\1520\1520_KOL_Cologne.inc"
include = "scenarios\1520\1520_KON_Kongo.inc"
include = "scenarios\1520\1520_KOR_Korea.inc"
include = "scenarios\1520\1520_KUT_Kutei.inc"
include = "scenarios\1520\1520_KZK_Kazakhs.inc"
include = "scenarios\1520\1520_LAT_Teutonic_Order.inc"
include = "scenarios\1520\1520_LAX_Lan_Xang.inc"
include = "scenarios\1520\1520_LIT_Lithuania.inc"
include = "scenarios\1520\1520_LIV_Livonian_Order.inc"
include = "scenarios\1520\1520_LNA_Lan_Na.inc"
include = "scenarios\1520\1520_LNK_Lanka.inc"
include = "scenarios\1520\1520_LOR_Lorraine.inc"
include = "scenarios\1520\1520_LUW_Luwu.inc"
include = "scenarios\1520\1520_MAI_Mainz.inc"
include = "scenarios\1520\1520_MAL_Mali.inc"
include = "scenarios\1520\1520_MAN_Mantua.inc"
include = "scenarios\1520\1520_MAS_Masovia.inc"
include = "scenarios\1520\1520_MCH_Manchus.inc"
include = "scenarios\1520\1520_MEC_Mecklenburg.inc"
include = "scenarios\1520\1520_MEI_Meissen.inc"
include = "scenarios\1520\1520_MGL_Mongolia.inc"
include = "scenarios\1520\1520_MGU_Mogadishu.inc"
include = "scenarios\1520\1520_MKS_Makassar.inc"
include = "scenarios\1520\1520_MLC_Malacca.inc"
include = "scenarios\1520\1520_MLI_Malindi.inc"
include = "scenarios\1520\1520_MLW_Malwa.inc"
include = "scenarios\1520\1520_MND_Magindanao.inc"
include = "scenarios\1520\1520_MOD_Modena.inc"
include = "scenarios\1520\1520_MOG_Mughal_Empire.inc"
include = "scenarios\1520\1520_MOL_Moldavia.inc"
include = "scenarios\1520\1520_MOM_Mombasa.inc"
include = "scenarios\1520\1520_MON_Mon.inc"
include = "scenarios\1520\1520_MOR_Morocco.inc"
include = "scenarios\1520\1520_MRA_Mahra.inc"
include = "scenarios\1520\1520_MSH_Musha'sha'.inc"
include = "scenarios\1520\1520_MTR_Mataram.inc"
include = "scenarios\1520\1520_MUB_Mu_Bang.inc"
include = "scenarios\1520\1520_NIP_Japan.inc"
include = "scenarios\1520\1520_NUB_Nubia.inc"
include = "scenarios\1520\1520_OLD_Oldenburg.inc"
include = "scenarios\1520\1520_ORI_Orissa.inc"
include = "scenarios\1520\1520_OYO_Oyo.inc"
include = "scenarios\1520\1520_PAK_Perak.inc"
include = "scenarios\1520\1520_PAL_Palembang.inc"
include = "scenarios\1520\1520_PAP_Papal_States.inc"
include = "scenarios\1520\1520_PER_Safavids.inc"
include = "scenarios\1520\1520_PFA_Palatinate.inc"
include = "scenarios\1520\1520_POL_Poland.inc"
include = "scenarios\1520\1520_POM_Pomerania.inc"
include = "scenarios\1520\1520_POR_Portugal.inc"
include = "scenarios\1520\1520_RAJ_Rajputana.inc"
include = "scenarios\1520\1520_RUS_Russia.inc"
include = "scenarios\1520\1520_RYA_Ryazan.inc"
include = "scenarios\1520\1520_SAC_Saxony.inc"
include = "scenarios\1520\1520_SAV_Savoy.inc"
include = "scenarios\1520\1520_SCO_Scotland.inc"
include = "scenarios\1520\1520_SHI_Shirvan.inc"
include = "scenarios\1520\1520_SHL_Holstein.inc"
include = "scenarios\1520\1520_SIB_Sibir.inc"
include = "scenarios\1520\1520_SIE_Siena.inc"
include = "scenarios\1520\1520_SIN_Sindh.inc"
include = "scenarios\1520\1520_SON_Songhai.inc"
include = "scenarios\1520\1520_SPA_Spain.inc"
include = "scenarios\1520\1520_STR_Strasburg.inc"
include = "scenarios\1520\1520_SUS_Sus.inc"
include = "scenarios\1520\1520_SWE_Sweden.inc"
include = "scenarios\1520\1520_TER_Ternate.inc"
include = "scenarios\1520\1520_TIB_Tibet.inc"
include = "scenarios\1520\1520_TLE_Tlemcen.inc"
include = "scenarios\1520\1520_TOS_Tuscany.inc"
include = "scenarios\1520\1520_TRV_Travancore.inc"
include = "scenarios\1520\1520_TUN_Tunisia.inc"
include = "scenarios\1520\1520_TUR_Ottoman_Empire.inc"
include = "scenarios\1520\1520_UZB_Uzbeks.inc"
include = "scenarios\1520\1520_VEN_Venice.inc"
include = "scenarios\1520\1520_VIJ_Vijayanagar.inc"
include = "scenarios\1520\1520_WAL_Wallachia.inc"
include = "scenarios\1520\1520_YEM_Yemen.inc"
include = "scenarios\1520\1520_ZAN_Zanzibar.inc"
include = "scenarios\1520\1520_ZAP_Zapotecs.inc"
include = "scenarios\1520\1520_ZIM_Zimbabwe.inc"

#-----------------------------------------------------------------------------------------------
#Rebel factions

country = {
	tag = REB
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R01
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R02
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R03
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R04
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R05
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = R06
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = NDR
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------

country = {
	tag = USR
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 10
	inflation = 0
	merchants = 0.0
	religion = { type = pagan }
	diplomacy = { }
	knownprovinces = { africa america asia europe oceania }
	ownedprovinces = {  }
	controlledprovinces = {  }
	nationalprovinces = {  }
	diplomats = 0
	technology = {
		stability = { level = 3 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
		group = pagan
	}
}

#-----------------------------------------------------------------------------------------------
